unit Udmcob;

interface

uses
 SysUtils,Messages, Classes,  FMTBcd, DB, DBClient, SimpleDS, SqlExpr,
  Provider, Dialogs, IniFiles, Forms, Data.DBXInterBase, Data.DBXFirebird,
  ACBrBoleto, ACBrBoletoFCFortesFr, ACBrBase, ACBrMail, ACBrExtenso,
  FireDAC.Stan.Intf, FireDAC.Stan.Option, FireDAC.Stan.Param,
  FireDAC.Stan.Error, FireDAC.DatS, FireDAC.Phys.Intf, FireDAC.DApt.Intf,
  FireDAC.Stan.Async, FireDAC.DApt, FireDAC.Comp.DataSet, FireDAC.Comp.Client, System.TypInfo,
  ACBrBoletoFCFR;

type
  TDMCOB = class(TDataModule)
    sds_cedentes: TSimpleDataSet;
    Dts_Cedentes: TDataSource;
    qryTitulos: TSQLQuery;
    sds_cedentesCODIGO_BOLETO: TIntegerField;
    sds_cedentesCOD_EMPRESA: TIntegerField;
    sds_cedentesDESCRICAO: TStringField;
    sds_cedentesBANCO_PORTADOR: TIntegerField;
    sds_cedentesQUANT_DIAS_PROTESTO: TSmallintField;
    sds_cedentesOBSERVACAO: TStringField;
    sds_cedentesLOCAL_PAGAMENTO: TStringField;
    sds_cedentesTIPO: TStringField;
    sds_cedentesNOMECEDENTE: TStringField;
    sds_cedentesCNPJCEDENTE: TStringField;
    sds_cedentesTIPOPESSOACEDENTE: TStringField;
    sds_cedentesCODIGOAGENCIA: TStringField;
    sds_cedentesDIGITOAGENCIA: TStringField;
    sds_cedentesNUMEROCONTA: TStringField;
    sds_cedentesDIGITOCONTA: TStringField;
    sds_cedentesCARTEIRA: TStringField;
    sds_cedentesCONVENIO: TStringField;
    sds_cedentesVLRABATIMENTO: TFloatField;
    sds_cedentesVLRDESCONTO: TFloatField;
    sds_cedentesVLRDESPESACOBRANCA: TFloatField;
    sds_cedentesVLRIOF: TFloatField;
    sds_cedentesVLRMORAJUROS: TFloatField;
    sds_cedentesVLROUTRASDEPESAS: TFloatField;
    sds_cedentesVLROUTROSCREDITOS: TFloatField;
    sds_cedentesFLAG_GERAR_REMESSA: TStringField;
    sds_cedentesNOSSONUMERO: TStringField;
    sds_cedentesNUMERO_REMESSA: TIntegerField;
    sds_cedentesANO_REFERENCIA: TStringField;
    sds_cedentesPROTESTAR_AUTOMATICO: TStringField;
    sds_cedentesMODELO: TStringField;
    sds_cedentesUSERCAD: TStringField;
    sds_cedentesDATACAD: TDateField;
    sds_cedentesNOME_AGENCIA: TStringField;
    sds_cedentesCEDENTECODIGODIGITO: TStringField;
    sds_cedentesCIDADE: TStringField;
    sds_cedentesENDERECO: TStringField;
    sds_cedentesUF: TStringField;
    sds_cedentesEMAIL: TStringField;
    sds_cedentesNUMERO: TIntegerField;
    sds_cedentesCEP: TStringField;
    sds_cedentesBAIRRO: TStringField;
    sds_cedentesCOMPLEMENTO: TStringField;
    sds_cedentesANO: TStringField;
    sds_cedentesTP_COBRANCA: TStringField;
    qryCedentes: TSQLQuery;
    Sds_Cobranca: TSimpleDataSet;
    dts_cobranca: TDataSource;
    Sds_CobrancaCODIGO: TIntegerField;
    Sds_CobrancaCODIGO_CLIENTE: TIntegerField;
    Sds_CobrancaDATA_COMPRA: TDateField;
    Sds_CobrancaDATA_VENCIMENTO: TDateField;
    Sds_CobrancaDATA_BAIXA: TDateField;
    Sds_CobrancaHISTORICO: TStringField;
    Sds_CobrancaUSUARIO_VENDA: TStringField;
    Sds_CobrancaUSUARIO_BAIXA: TStringField;
    Sds_CobrancaSITUACAO: TStringField;
    Sds_CobrancaVALOR_COMPRA: TFMTBCDField;
    Sds_CobrancaVALOR_JUROS: TFMTBCDField;
    Sds_CobrancaVALOR_ACRESCIMO: TFMTBCDField;
    Sds_CobrancaVALOR_DESCONTO: TFMTBCDField;
    Sds_CobrancaVALOR_PAGAR: TFMTBCDField;
    Sds_CobrancaVALOR_PAGO: TFMTBCDField;
    Sds_CobrancaVALOR_TOTAL: TFMTBCDField;
    Sds_CobrancaCODIGO_COMPRA: TIntegerField;
    Sds_CobrancaPARCELA: TStringField;
    Sds_CobrancaNUMBOLETO: TStringField;
    Sds_CobrancaBANCO_PORTADOR: TIntegerField;
    Sds_CobrancaREMESSA: TStringField;
    Sds_CobrancaDATACREDITO: TDateField;
    Sds_CobrancaID_PORTADOR: TIntegerField;
    sds_cedentesLOGO: TBlobField;
    Sds_CobrancaENVIADO: TStringField;
    Sds_CobrancaCOD_EMPRESA: TIntegerField;
    Sds_CobrancaNUMBOLETO1: TIntegerField;
    SQLD_Cobranca: TSQLDataSet;
    SQLD_CobrancaCODIGO: TIntegerField;
    SQLD_CobrancaCODIGO_CLIENTE: TIntegerField;
    SQLD_CobrancaDATA_COMPRA: TDateField;
    SQLD_CobrancaDATA_VENCIMENTO: TDateField;
    SQLD_CobrancaDATA_BAIXA: TDateField;
    SQLD_CobrancaHISTORICO: TStringField;
    SQLD_CobrancaUSUARIO_VENDA: TStringField;
    SQLD_CobrancaUSUARIO_BAIXA: TStringField;
    SQLD_CobrancaSITUACAO: TStringField;
    SQLD_CobrancaVALOR_COMPRA: TFMTBCDField;
    SQLD_CobrancaVALOR_JUROS: TFMTBCDField;
    SQLD_CobrancaVALOR_ACRESCIMO: TFMTBCDField;
    SQLD_CobrancaVALOR_DESCONTO: TFMTBCDField;
    SQLD_CobrancaVALOR_PAGAR: TFMTBCDField;
    SQLD_CobrancaVALOR_PAGO: TFMTBCDField;
    SQLD_CobrancaVALOR_TOTAL: TFMTBCDField;
    SQLD_CobrancaCODIGO_COMPRA: TIntegerField;
    SQLD_CobrancaPARCELA: TStringField;
    SQLD_CobrancaNUMBOLETO: TStringField;
    SQLD_CobrancaBANCO_PORTADOR: TIntegerField;
    SQLD_CobrancaREMESSA: TStringField;
    SQLD_CobrancaDATACREDITO: TDateField;
    SQLD_CobrancaID_PORTADOR: TIntegerField;
    SQLD_CobrancaENVIADO: TStringField;
    SQLD_CobrancaCOD_EMPRESA: TIntegerField;
    SQLD_CobrancaNUMBOLETO1: TIntegerField;
    DTSP_COBRANCA: TDataSetProvider;
    CDS_COBRANCA: TClientDataSet;
    DTS_Titulos: TDataSource;
    SDS_Titulos: TSimpleDataSet;
    SDS_TitulosCODIGO: TIntegerField;
    SDS_TitulosCODIGO_CLIENTE: TIntegerField;
    SDS_TitulosDATA_COMPRA: TDateField;
    SDS_TitulosDATA_VENCIMENTO: TDateField;
    SDS_TitulosDATA_BAIXA: TDateField;
    SDS_TitulosHISTORICO: TStringField;
    SDS_TitulosUSUARIO_VENDA: TStringField;
    SDS_TitulosUSUARIO_BAIXA: TStringField;
    SDS_TitulosSITUACAO: TStringField;
    SDS_TitulosVALOR_COMPRA: TFMTBCDField;
    SDS_TitulosVALOR_JUROS: TFMTBCDField;
    SDS_TitulosVALOR_ACRESCIMO: TFMTBCDField;
    SDS_TitulosVALOR_DESCONTO: TFMTBCDField;
    SDS_TitulosVALOR_PAGAR: TFMTBCDField;
    SDS_TitulosVALOR_PAGO: TFMTBCDField;
    SDS_TitulosVALOR_TOTAL: TFMTBCDField;
    SDS_TitulosCODIGO_COMPRA: TIntegerField;
    SDS_TitulosPARCELA: TStringField;
    SDS_TitulosNUMBOLETO: TStringField;
    SDS_TitulosBANCO_PORTADOR: TIntegerField;
    SDS_TitulosREMESSA: TStringField;
    SDS_TitulosDATACREDITO: TDateField;
    SDS_TitulosID_PORTADOR: TIntegerField;
    SDS_TitulosENVIADO: TStringField;
    SDS_TitulosCOD_EMPRESA: TIntegerField;
    SDS_TitulosNUMBOLETO1: TIntegerField;
    cds_titulos: TClientDataSet;
    DTSP_Titulos: TDataSetProvider;
    dts_cobranca1: TDataSource;
    qryCobranca1: TSQLQuery;
    qryCobranca1CODIGO: TIntegerField;
    qryCobranca1CODIGO_CLIENTE: TIntegerField;
    qryCobranca1DATA_COMPRA: TDateField;
    qryCobranca1DATA_VENCIMENTO: TDateField;
    qryCobranca1DATA_BAIXA: TDateField;
    qryCobranca1HISTORICO: TStringField;
    qryCobranca1USUARIO_BAIXA: TStringField;
    qryCobranca1SITUACAO: TStringField;
    qryCobranca1VALOR_COMPRA: TFMTBCDField;
    qryCobranca1VALOR_JUROS: TFMTBCDField;
    qryCobranca1VALOR_ACRESCIMO: TFMTBCDField;
    qryCobranca1VALOR_DESCONTO: TFMTBCDField;
    qryCobranca1VALOR_PAGAR: TFMTBCDField;
    qryCobranca1VALOR_PAGO: TFMTBCDField;
    qryCobranca1VALOR_TOTAL: TFMTBCDField;
    qryCobranca1CODIGO_COMPRA: TIntegerField;
    qryCobranca1PARCELA: TStringField;
    qryCobranca1NUMBOLETO: TStringField;
    qryCobranca1BANCO_PORTADOR: TIntegerField;
    qryCobranca1DATACREDITO: TDateField;
    qryCobranca1ID_PORTADOR: TIntegerField;
    qryCobranca1ENVIADO: TStringField;
    qryCobranca1COD_EMPRESA: TIntegerField;
    qryCobranca1NUMBOLETO1: TIntegerField;
    CDS_COBRANCA1: TClientDataSet;
    DTSP_COBRANCA1: TDataSetProvider;
    CDS_COBRANCA1CODIGO: TIntegerField;
    CDS_COBRANCA1CODIGO_CLIENTE: TIntegerField;
    CDS_COBRANCA1DATA_COMPRA: TDateField;
    CDS_COBRANCA1DATA_VENCIMENTO: TDateField;
    CDS_COBRANCA1DATA_BAIXA: TDateField;
    CDS_COBRANCA1HISTORICO: TStringField;
    CDS_COBRANCA1USUARIO_VENDA: TStringField;
    CDS_COBRANCA1USUARIO_BAIXA: TStringField;
    CDS_COBRANCA1SITUACAO: TStringField;
    CDS_COBRANCA1VALOR_COMPRA: TFMTBCDField;
    CDS_COBRANCA1VALOR_JUROS: TFMTBCDField;
    CDS_COBRANCA1VALOR_ACRESCIMO: TFMTBCDField;
    CDS_COBRANCA1VALOR_DESCONTO: TFMTBCDField;
    CDS_COBRANCA1VALOR_PAGAR: TFMTBCDField;
    CDS_COBRANCA1VALOR_PAGO: TFMTBCDField;
    CDS_COBRANCA1VALOR_TOTAL: TFMTBCDField;
    CDS_COBRANCA1CODIGO_COMPRA: TIntegerField;
    CDS_COBRANCA1PARCELA: TStringField;
    CDS_COBRANCA1NUMBOLETO: TStringField;
    CDS_COBRANCA1BANCO_PORTADOR: TIntegerField;
    CDS_COBRANCA1REMESSA: TStringField;
    CDS_COBRANCA1DATACREDITO: TDateField;
    CDS_COBRANCA1ID_PORTADOR: TIntegerField;
    CDS_COBRANCA1ENVIADO: TStringField;
    CDS_COBRANCA1COD_EMPRESA: TIntegerField;
    CDS_COBRANCA1NUMBOLETO1: TIntegerField;
    CDS_COBRANCACODIGO: TIntegerField;
    CDS_COBRANCACODIGO_CLIENTE: TIntegerField;
    CDS_COBRANCADATA_COMPRA: TDateField;
    CDS_COBRANCADATA_VENCIMENTO: TDateField;
    CDS_COBRANCADATA_BAIXA: TDateField;
    CDS_COBRANCAHISTORICO: TStringField;
    CDS_COBRANCAUSUARIO_VENDA: TStringField;
    CDS_COBRANCAUSUARIO_BAIXA: TStringField;
    CDS_COBRANCASITUACAO: TStringField;
    CDS_COBRANCAVALOR_COMPRA: TFMTBCDField;
    CDS_COBRANCAVALOR_JUROS: TFMTBCDField;
    CDS_COBRANCAVALOR_ACRESCIMO: TFMTBCDField;
    CDS_COBRANCAVALOR_DESCONTO: TFMTBCDField;
    CDS_COBRANCAVALOR_PAGAR: TFMTBCDField;
    CDS_COBRANCAVALOR_PAGO: TFMTBCDField;
    CDS_COBRANCAVALOR_TOTAL: TFMTBCDField;
    CDS_COBRANCACODIGO_COMPRA: TIntegerField;
    CDS_COBRANCAPARCELA: TStringField;
    CDS_COBRANCANUMBOLETO: TStringField;
    CDS_COBRANCABANCO_PORTADOR: TIntegerField;
    CDS_COBRANCAREMESSA: TStringField;
    CDS_COBRANCADATACREDITO: TDateField;
    CDS_COBRANCAID_PORTADOR: TIntegerField;
    CDS_COBRANCAENVIADO: TStringField;
    CDS_COBRANCACOD_EMPRESA: TIntegerField;
    CDS_COBRANCANUMBOLETO1: TIntegerField;
    sds_cedentesCEDENTECODIGO: TStringField;
    Sds_CobrancaCODIGOCEDENTE: TStringField;
    CDS_COBRANCACODIGOCEDENTE: TStringField;
    qryCobranca1CODIGOCEDENTE: TStringField;
    CDS_COBRANCA1CODIGOCEDENTE: TStringField;
    qryCedentesCODIGO_BOLETO: TIntegerField;
    qryCedentesCOD_EMPRESA: TIntegerField;
    qryCedentesDESCRICAO: TStringField;
    qryCedentesBANCO_PORTADOR: TIntegerField;
    qryCedentesQUANT_DIAS_PROTESTO: TSmallintField;
    qryCedentesOBSERVACAO: TStringField;
    qryCedentesLOCAL_PAGAMENTO: TStringField;
    qryCedentesTIPO: TStringField;
    qryCedentesNOMECEDENTE: TStringField;
    qryCedentesCNPJCEDENTE: TStringField;
    qryCedentesTIPOPESSOACEDENTE: TStringField;
    qryCedentesCODIGOAGENCIA: TStringField;
    qryCedentesDIGITOAGENCIA: TStringField;
    qryCedentesNUMEROCONTA: TStringField;
    qryCedentesDIGITOCONTA: TStringField;
    qryCedentesCARTEIRA: TStringField;
    qryCedentesCONVENIO: TStringField;
    qryCedentesVLRABATIMENTO: TFloatField;
    qryCedentesVLRDESCONTO: TFloatField;
    qryCedentesVLRDESPESACOBRANCA: TFloatField;
    qryCedentesVLRIOF: TFloatField;
    qryCedentesVLRMORAJUROS: TFloatField;
    qryCedentesVLROUTRASDEPESAS: TFloatField;
    qryCedentesVLROUTROSCREDITOS: TFloatField;
    qryCedentesFLAG_GERAR_REMESSA: TStringField;
    qryCedentesNOSSONUMERO: TStringField;
    qryCedentesNUMERO_REMESSA: TIntegerField;
    qryCedentesANO_REFERENCIA: TStringField;
    qryCedentesPROTESTAR_AUTOMATICO: TStringField;
    qryCedentesMODELO: TStringField;
    qryCedentesUSERCAD: TStringField;
    qryCedentesDATACAD: TDateField;
    qryCedentesNOME_AGENCIA: TStringField;
    qryCedentesCEDENTECODIGO: TStringField;
    qryCedentesCEDENTECODIGODIGITO: TStringField;
    qryCedentesCIDADE: TStringField;
    qryCedentesENDERECO: TStringField;
    qryCedentesUF: TStringField;
    qryCedentesEMAIL: TStringField;
    qryCedentesNUMERO: TIntegerField;
    qryCedentesCEP: TStringField;
    qryCedentesBAIRRO: TStringField;
    qryCedentesCOMPLEMENTO: TStringField;
    qryCedentesANO: TStringField;
    qryCedentesTP_COBRANCA: TStringField;
    qryCedentesLOGO: TBlobField;
    dts_Cedentes1: TDataSource;
    qryCobranca1TIPO: TStringField;
    qryCobranca1CHEK_BOX: TStringField;
    CDS_COBRANCA1TIPO: TStringField;
    CDS_COBRANCA1CHEK_BOX: TStringField;
    Sds_CobrancaTIPO: TStringField;
    Sds_CobrancaCHEK_BOX: TStringField;
    qryCobranca1NUM_NOTA: TIntegerField;
    qryCobranca1SERIE_NOTA: TStringField;
    CDS_COBRANCA1NUM_NOTA: TIntegerField;
    CDS_COBRANCA1SERIE_NOTA: TStringField;
    qryCobranca1NOME_SACADO: TStringField;
    CDS_COBRANCA1NOME_SACADO: TStringField;
    sds_clientes: TSimpleDataSet;
    Dts_clientes: TDataSource;
    sds_clientesCODIGO: TIntegerField;
    sds_clientesNOME_RS: TStringField;
    sds_clientesENDERECO: TStringField;
    sds_clientesCIDADE: TStringField;
    sds_clientesUF: TStringField;
    sds_clientesCEP: TStringField;
    sds_clientesTELEFONE: TStringField;
    sds_clientesTELEFONE2: TStringField;
    sds_clientesEMAIL: TStringField;
    sds_clientesNASCIMENTO_IA: TDateField;
    sds_clientesSEXO: TStringField;
    sds_clientesFOTO_LOGOMARCA: TBlobField;
    sds_clientesBAIRRO: TStringField;
    sds_clientesRG_IE: TStringField;
    sds_clientesFAX: TStringField;
    sds_clientesCELULAR: TStringField;
    sds_clientesUSERCAD: TStringField;
    sds_clientesDATACAD: TDateField;
    sds_clientesCPF_CNPJ: TStringField;
    sds_clientesOBSERVACOES: TBlobField;
    sds_clientesCREDIARIO: TStringField;
    sds_clientesESTADOCIVIL: TStringField;
    sds_clientesRESIDENCIA_SEDE: TStringField;
    sds_clientesPAI: TStringField;
    sds_clientesMAE: TStringField;
    sds_clientesNOME_CONJUGE: TStringField;
    sds_clientesCPF_CONJUGE: TStringField;
    sds_clientesNASCIMENTO_CONJUGE: TDateField;
    sds_clientesTRABALHO_CONJUGE: TStringField;
    sds_clientesPROFISSAO_CONJUGE: TStringField;
    sds_clientesLOCALTRABALHO: TStringField;
    sds_clientesPROFISSAO_RA: TStringField;
    sds_clientesTELEFONE_TRABALHO: TStringField;
    sds_clientesFAX_TRABALHO: TStringField;
    sds_clientesOBSERVACOES_TRABALHO: TBlobField;
    sds_clientesBANCO: TStringField;
    sds_clientesNOME_AGENCIA: TStringField;
    sds_clientesNUMERO_AGENCIA: TStringField;
    sds_clientesCONTA_CORRENTE: TIntegerField;
    sds_clientesNOME1_REFERENCIA: TStringField;
    sds_clientesNOME2_REFERENCIA: TStringField;
    sds_clientesTELEFONE1_REFERENCIA: TStringField;
    sds_clientesTELEFONE2_REFERENCIA: TStringField;
    sds_clientesBANCO_REFERENCIA: TStringField;
    sds_clientesAPELIDO: TStringField;
    sds_clientesTIPO: TStringField;
    sds_clientesOBSERVACOES_COMERCIAIS: TBlobField;
    sds_clientesOBSERVACOES_BANCO: TBlobField;
    sds_clientesPG_CREDIARIO: TStringField;
    sds_clientesPG_CHEQUE: TStringField;
    sds_clientesPG_FINANCEIRA: TStringField;
    sds_clientesREMUNERACAO: TFMTBCDField;
    sds_clientesNUMERO: TStringField;
    sds_clientesCOMPLEMENTO: TStringField;
    sds_clientesCOD_EMPRESA: TIntegerField;
    sds_clientesORGAO_EMISSOR: TStringField;
    sds_clientesDATA_EMISSAO_RG: TDateField;
    sds_clientesNATURALIDADE: TStringField;
    sds_clientesNATURALIDADE_UF: TStringField;
    sds_clientesCOD_CIDADE: TIntegerField;
    sds_clientesCOD_BAIRRO: TIntegerField;
    sds_clientesDATA_ALTERACAO: TDateField;
    sds_clientesCOD_ZONA: TIntegerField;
    sds_clientesPONTO_REFERENCIA: TStringField;
    sds_clientesATIVO: TStringField;
    sds_clientesCONTATO1: TStringField;
    sds_clientesCONTATO2: TStringField;
    sds_clientesCX_POSTAL: TStringField;
    sds_clientesVALOR_ALUGUEL: TFMTBCDField;
    sds_clientesTEMPO_RESIDENCIA: TStringField;
    sds_clientesNUMERO_DEPENDENTES: TIntegerField;
    sds_clientesENDERECO_REFERENCIA1: TStringField;
    sds_clientesENDERECO_REFERENCIA2: TStringField;
    sds_clientesDATA_ADMISSAO_REFERENCIA1: TDateField;
    sds_clientesDATA_ADMISSAO_REFERENCIA2: TDateField;
    sds_clientesRG_CONJUGUE: TStringField;
    sds_clientesRENDA_CONJUGUE: TFMTBCDField;
    sds_clientesDATA_ADMINSSAO_CONJUGUE: TDateField;
    sds_clientesFONE_CONJUGUE: TStringField;
    sds_clientesENDERECO_COBRANCA: TStringField;
    sds_clientesCEP_COBRANCA: TStringField;
    sds_clientesCOD_CIDADE_COBRANCA: TIntegerField;
    sds_clientesCX_POSTAL_COBRANCA: TStringField;
    sds_clientesLIMITE_DE_CREDITO: TFMTBCDField;
    sds_clientesINSC_MUNICIPAL: TStringField;
    sds_clientesPRODUTOR_RURAL: TStringField;
    sds_clientesINSC_PRODUTOR_RURAL: TStringField;
    sds_clientesCOD_BAIRRO_COBRANCA: TIntegerField;
    sds_clientesCIDADE_COBRANCA: TStringField;
    sds_clientesBAIRRO_COBRANCA: TStringField;
    sds_clientesUF_COBRANCA: TStringField;
    SDS_TitulosCODIGOCEDENTE: TStringField;
    SDS_TitulosTIPO: TStringField;
    SDS_TitulosCHEK_BOX: TStringField;
    SDS_TitulosNUM_NOTA: TIntegerField;
    SDS_TitulosSERIE_NOTA: TStringField;
    SDS_TitulosNOME_SACADO: TStringField;
    Dts_cobranca2: TDataSource;
    cds_cobranca2: TClientDataSet;
    dtsp_cobranca2: TDataSetProvider;
    QryCobranca2: TSQLQuery;
    IntegerField9: TIntegerField;
    IntegerField10: TIntegerField;
    DateField5: TDateField;
    DateField6: TDateField;
    DateField7: TDateField;
    StringField14: TStringField;
    StringField15: TStringField;
    StringField16: TStringField;
    StringField17: TStringField;
    FMTBCDField8: TFMTBCDField;
    FMTBCDField9: TFMTBCDField;
    FMTBCDField10: TFMTBCDField;
    FMTBCDField11: TFMTBCDField;
    FMTBCDField12: TFMTBCDField;
    FMTBCDField13: TFMTBCDField;
    FMTBCDField14: TFMTBCDField;
    IntegerField11: TIntegerField;
    StringField18: TStringField;
    StringField19: TStringField;
    IntegerField12: TIntegerField;
    StringField20: TStringField;
    DateField8: TDateField;
    IntegerField13: TIntegerField;
    StringField21: TStringField;
    IntegerField14: TIntegerField;
    IntegerField15: TIntegerField;
    StringField22: TStringField;
    StringField23: TStringField;
    StringField24: TStringField;
    IntegerField16: TIntegerField;
    StringField25: TStringField;
    StringField26: TStringField;
    Dts_clientes2: TDataSource;
    Sds_clientes2: TSimpleDataSet;
    IntegerField17: TIntegerField;
    StringField27: TStringField;
    StringField28: TStringField;
    StringField29: TStringField;
    StringField30: TStringField;
    StringField31: TStringField;
    StringField32: TStringField;
    StringField33: TStringField;
    StringField34: TStringField;
    DateField9: TDateField;
    StringField35: TStringField;
    BlobField1: TBlobField;
    StringField36: TStringField;
    StringField37: TStringField;
    StringField38: TStringField;
    StringField39: TStringField;
    StringField40: TStringField;
    DateField10: TDateField;
    StringField41: TStringField;
    BlobField2: TBlobField;
    StringField42: TStringField;
    StringField43: TStringField;
    StringField44: TStringField;
    StringField45: TStringField;
    StringField46: TStringField;
    StringField47: TStringField;
    StringField48: TStringField;
    DateField11: TDateField;
    StringField49: TStringField;
    StringField50: TStringField;
    StringField51: TStringField;
    StringField52: TStringField;
    StringField53: TStringField;
    StringField54: TStringField;
    BlobField3: TBlobField;
    StringField55: TStringField;
    StringField56: TStringField;
    StringField57: TStringField;
    IntegerField18: TIntegerField;
    StringField58: TStringField;
    StringField59: TStringField;
    StringField60: TStringField;
    StringField61: TStringField;
    StringField62: TStringField;
    StringField63: TStringField;
    StringField64: TStringField;
    BlobField4: TBlobField;
    BlobField5: TBlobField;
    StringField65: TStringField;
    StringField66: TStringField;
    StringField67: TStringField;
    FMTBCDField15: TFMTBCDField;
    StringField68: TStringField;
    StringField69: TStringField;
    IntegerField19: TIntegerField;
    StringField70: TStringField;
    DateField12: TDateField;
    StringField71: TStringField;
    StringField72: TStringField;
    IntegerField20: TIntegerField;
    IntegerField21: TIntegerField;
    DateField13: TDateField;
    IntegerField22: TIntegerField;
    StringField73: TStringField;
    StringField74: TStringField;
    StringField75: TStringField;
    StringField76: TStringField;
    StringField77: TStringField;
    FMTBCDField16: TFMTBCDField;
    StringField78: TStringField;
    IntegerField23: TIntegerField;
    StringField79: TStringField;
    StringField80: TStringField;
    DateField14: TDateField;
    DateField15: TDateField;
    StringField81: TStringField;
    FMTBCDField17: TFMTBCDField;
    DateField16: TDateField;
    StringField82: TStringField;
    StringField83: TStringField;
    StringField84: TStringField;
    IntegerField24: TIntegerField;
    StringField85: TStringField;
    FMTBCDField18: TFMTBCDField;
    StringField86: TStringField;
    StringField87: TStringField;
    StringField88: TStringField;
    IntegerField25: TIntegerField;
    StringField89: TStringField;
    StringField90: TStringField;
    StringField91: TStringField;
    cds_cobranca2CODIGO: TIntegerField;
    cds_cobranca2CODIGO_CLIENTE: TIntegerField;
    cds_cobranca2DATA_COMPRA: TDateField;
    cds_cobranca2DATA_VENCIMENTO: TDateField;
    cds_cobranca2DATA_BAIXA: TDateField;
    cds_cobranca2HISTORICO: TStringField;
    cds_cobranca2USUARIO_VENDA: TStringField;
    cds_cobranca2USUARIO_BAIXA: TStringField;
    cds_cobranca2SITUACAO: TStringField;
    cds_cobranca2VALOR_COMPRA: TFMTBCDField;
    cds_cobranca2VALOR_JUROS: TFMTBCDField;
    cds_cobranca2VALOR_ACRESCIMO: TFMTBCDField;
    cds_cobranca2VALOR_DESCONTO: TFMTBCDField;
    cds_cobranca2VALOR_PAGAR: TFMTBCDField;
    cds_cobranca2VALOR_PAGO: TFMTBCDField;
    cds_cobranca2VALOR_TOTAL: TFMTBCDField;
    cds_cobranca2CODIGO_COMPRA: TIntegerField;
    cds_cobranca2PARCELA: TStringField;
    cds_cobranca2NUMBOLETO: TStringField;
    cds_cobranca2BANCO_PORTADOR: TIntegerField;
    cds_cobranca2REMESSA: TStringField;
    cds_cobranca2DATACREDITO: TDateField;
    cds_cobranca2ID_PORTADOR: TIntegerField;
    cds_cobranca2ENVIADO: TStringField;
    cds_cobranca2COD_EMPRESA: TIntegerField;
    cds_cobranca2NUMBOLETO1: TIntegerField;
    cds_cobranca2CODIGOCEDENTE: TStringField;
    cds_cobranca2TIPO: TStringField;
    cds_cobranca2CHEK_BOX: TStringField;
    cds_cobranca2NUM_NOTA: TIntegerField;
    cds_cobranca2SERIE_NOTA: TStringField;
    cds_cobranca2NOME_SACADO: TStringField;
    qryCobranca1ID_CONTRATO: TIntegerField;
    QryCobranca2ID_CONTRATO: TIntegerField;
    CDS_COBRANCA1ID_CONTRATO: TIntegerField;
    cds_cobranca2ID_CONTRATO: TIntegerField;
    Sds_CobrancaNUM_NOTA: TIntegerField;
    Sds_CobrancaSERIE_NOTA: TStringField;
    Sds_CobrancaNOME_SACADO: TStringField;
    Sds_CobrancaANO: TStringField;
    Sds_CobrancaMES: TStringField;
    Sds_CobrancaTP_BAIXA: TStringField;
    Sds_CobrancaID_CONTRATO: TIntegerField;
    SDS_TitulosID_CONTRATO: TIntegerField;
    qryCobranca1USUARIO_VENDA: TStringField;
    qryCobranca1REMESSA: TStringField;
    qryCobranca1COBRADOR: TIntegerField;
    CDS_COBRANCA1COBRADOR: TIntegerField;
    CDS_COBRANCA1NomeCobrador: TStringField;
    QryCobranca2COBRADOR: TIntegerField;
    cds_cobranca2COBRADOR: TIntegerField;
    qryCobranca1COMISSAO: TFMTBCDField;
    CDS_COBRANCA1COMISSAO: TFMTBCDField;
    QryCobranca2COMISSAO: TFMTBCDField;
    cds_cobranca2COMISSAO: TFMTBCDField;
    Sds_CobrancaNOME_ARQ: TStringField;
    Sds_CobrancaCOBRADOR: TIntegerField;
    Sds_CobrancaCOMISSAO: TFMTBCDField;
    cds_cobranca2DT_PREVISAO_PGTO: TDateField;
    QryCobranca2DT_PREVISAO_PGTO: TDateField;
    qryCobranca1DT_PREVISAO_PGTO: TDateField;
    CDS_COBRANCA1DT_PREVISAO_PGTO: TDateField;
    qryCobranca1DIAS_VENCIDO: TIntegerField;
    CDS_COBRANCA1DIAS_VENCIDO: TIntegerField;
    QryCobranca2DIAS_VENCIDO: TIntegerField;
    cds_cobranca2DIAS_VENCIDO: TIntegerField;
    qryCobranca3: TSQLQuery;
    IntegerField1: TIntegerField;
    IntegerField2: TIntegerField;
    DateField1: TDateField;
    DateField2: TDateField;
    DateField3: TDateField;
    StringField1: TStringField;
    StringField2: TStringField;
    StringField3: TStringField;
    FMTBCDField1: TFMTBCDField;
    FMTBCDField2: TFMTBCDField;
    FMTBCDField3: TFMTBCDField;
    FMTBCDField4: TFMTBCDField;
    FMTBCDField5: TFMTBCDField;
    FMTBCDField6: TFMTBCDField;
    FMTBCDField7: TFMTBCDField;
    IntegerField3: TIntegerField;
    StringField4: TStringField;
    StringField5: TStringField;
    IntegerField4: TIntegerField;
    DateField4: TDateField;
    IntegerField5: TIntegerField;
    StringField6: TStringField;
    IntegerField6: TIntegerField;
    IntegerField7: TIntegerField;
    StringField7: TStringField;
    StringField8: TStringField;
    StringField9: TStringField;
    IntegerField8: TIntegerField;
    StringField10: TStringField;
    StringField11: TStringField;
    IntegerField26: TIntegerField;
    StringField12: TStringField;
    StringField13: TStringField;
    IntegerField27: TIntegerField;
    FMTBCDField19: TFMTBCDField;
    DateField17: TDateField;
    IntegerField28: TIntegerField;
    DTSP_COBRANCA3: TDataSetProvider;
    CDS_COBRANCA3: TClientDataSet;
    dts_cobranca3: TDataSource;
    sds_clientes3: TSimpleDataSet;
    IntegerField40: TIntegerField;
    StringField106: TStringField;
    StringField107: TStringField;
    StringField108: TStringField;
    StringField109: TStringField;
    StringField110: TStringField;
    StringField111: TStringField;
    StringField112: TStringField;
    StringField113: TStringField;
    DateField23: TDateField;
    StringField114: TStringField;
    BlobField6: TBlobField;
    StringField115: TStringField;
    StringField116: TStringField;
    StringField117: TStringField;
    StringField118: TStringField;
    StringField119: TStringField;
    DateField24: TDateField;
    StringField120: TStringField;
    BlobField7: TBlobField;
    StringField121: TStringField;
    StringField122: TStringField;
    StringField123: TStringField;
    StringField124: TStringField;
    StringField125: TStringField;
    StringField126: TStringField;
    StringField127: TStringField;
    DateField25: TDateField;
    StringField128: TStringField;
    StringField129: TStringField;
    StringField130: TStringField;
    StringField131: TStringField;
    StringField132: TStringField;
    StringField133: TStringField;
    BlobField8: TBlobField;
    StringField134: TStringField;
    StringField135: TStringField;
    StringField136: TStringField;
    IntegerField41: TIntegerField;
    StringField137: TStringField;
    StringField138: TStringField;
    StringField139: TStringField;
    StringField140: TStringField;
    StringField141: TStringField;
    StringField142: TStringField;
    StringField143: TStringField;
    BlobField9: TBlobField;
    BlobField10: TBlobField;
    StringField144: TStringField;
    StringField145: TStringField;
    StringField146: TStringField;
    FMTBCDField28: TFMTBCDField;
    StringField147: TStringField;
    StringField148: TStringField;
    IntegerField42: TIntegerField;
    StringField149: TStringField;
    DateField26: TDateField;
    StringField150: TStringField;
    StringField151: TStringField;
    IntegerField43: TIntegerField;
    IntegerField44: TIntegerField;
    DateField27: TDateField;
    IntegerField45: TIntegerField;
    StringField152: TStringField;
    StringField153: TStringField;
    StringField154: TStringField;
    StringField155: TStringField;
    StringField156: TStringField;
    FMTBCDField29: TFMTBCDField;
    StringField157: TStringField;
    IntegerField46: TIntegerField;
    StringField158: TStringField;
    StringField159: TStringField;
    DateField28: TDateField;
    DateField29: TDateField;
    StringField160: TStringField;
    FMTBCDField30: TFMTBCDField;
    DateField30: TDateField;
    StringField161: TStringField;
    StringField162: TStringField;
    StringField163: TStringField;
    IntegerField47: TIntegerField;
    StringField164: TStringField;
    FMTBCDField31: TFMTBCDField;
    StringField165: TStringField;
    StringField166: TStringField;
    StringField167: TStringField;
    IntegerField48: TIntegerField;
    StringField168: TStringField;
    StringField169: TStringField;
    StringField170: TStringField;
    Dts_clientes3: TDataSource;
    qryCobranca3MES: TStringField;
    qryCobranca3TP_BAIXA: TStringField;
    qryCobranca3NOME_ARQ: TStringField;
    qryCobranca3N_OS: TStringField;
    qryCobranca3VLR_GRAFICA: TFMTBCDField;
    qryCobranca3VALOR_COMISAO: TFMTBCDField;
    qryCobranca3NOME_RS: TStringField;
    qryCobranca3CIDADE: TStringField;
    qryCobranca3UF: TStringField;
    qryCobranca3COD_ZONA: TIntegerField;
    qryCobranca3DESCRICAO: TStringField;
    CDS_COBRANCA3CODIGO: TIntegerField;
    CDS_COBRANCA3CODIGO_CLIENTE: TIntegerField;
    CDS_COBRANCA3DATA_COMPRA: TDateField;
    CDS_COBRANCA3DATA_VENCIMENTO: TDateField;
    CDS_COBRANCA3DATA_BAIXA: TDateField;
    CDS_COBRANCA3HISTORICO: TStringField;
    CDS_COBRANCA3USUARIO_BAIXA: TStringField;
    CDS_COBRANCA3SITUACAO: TStringField;
    CDS_COBRANCA3VALOR_COMPRA: TFMTBCDField;
    CDS_COBRANCA3VALOR_JUROS: TFMTBCDField;
    CDS_COBRANCA3VALOR_ACRESCIMO: TFMTBCDField;
    CDS_COBRANCA3VALOR_DESCONTO: TFMTBCDField;
    CDS_COBRANCA3VALOR_PAGAR: TFMTBCDField;
    CDS_COBRANCA3VALOR_PAGO: TFMTBCDField;
    CDS_COBRANCA3VALOR_TOTAL: TFMTBCDField;
    CDS_COBRANCA3CODIGO_COMPRA: TIntegerField;
    CDS_COBRANCA3PARCELA: TStringField;
    CDS_COBRANCA3NUMBOLETO: TStringField;
    CDS_COBRANCA3BANCO_PORTADOR: TIntegerField;
    CDS_COBRANCA3DATACREDITO: TDateField;
    CDS_COBRANCA3ID_PORTADOR: TIntegerField;
    CDS_COBRANCA3ENVIADO: TStringField;
    CDS_COBRANCA3COD_EMPRESA: TIntegerField;
    CDS_COBRANCA3NUMBOLETO1: TIntegerField;
    CDS_COBRANCA3CODIGOCEDENTE: TStringField;
    CDS_COBRANCA3TIPO: TStringField;
    CDS_COBRANCA3CHEK_BOX: TStringField;
    CDS_COBRANCA3NUM_NOTA: TIntegerField;
    CDS_COBRANCA3SERIE_NOTA: TStringField;
    CDS_COBRANCA3NOME_SACADO: TStringField;
    CDS_COBRANCA3ID_CONTRATO: TIntegerField;
    CDS_COBRANCA3USUARIO_VENDA: TStringField;
    CDS_COBRANCA3REMESSA: TStringField;
    CDS_COBRANCA3COBRADOR: TIntegerField;
    CDS_COBRANCA3COMISSAO: TFMTBCDField;
    CDS_COBRANCA3DT_PREVISAO_PGTO: TDateField;
    CDS_COBRANCA3DIAS_VENCIDO: TIntegerField;
    CDS_COBRANCA3ANO: TStringField;
    CDS_COBRANCA3MES: TStringField;
    CDS_COBRANCA3TP_BAIXA: TStringField;
    CDS_COBRANCA3NOME_ARQ: TStringField;
    CDS_COBRANCA3N_OS: TStringField;
    CDS_COBRANCA3VLR_GRAFICA: TFMTBCDField;
    CDS_COBRANCA3VALOR_COMISAO: TFMTBCDField;
    CDS_COBRANCA3NOME_RS: TStringField;
    CDS_COBRANCA3CIDADE: TStringField;
    CDS_COBRANCA3UF: TStringField;
    CDS_COBRANCA3COD_ZONA: TIntegerField;
    qryCobranca3ANO: TStringField;
    qryCobranca3ID_CONTRATO1: TIntegerField;
    qryCobranca3DESCRICAO1: TStringField;
    qryCobranca3ID_PLANO: TIntegerField;
    CDS_COBRANCA3DESCRICAO: TStringField;
    CDS_COBRANCA3ID_CONTRATO1: TIntegerField;
    CDS_COBRANCA3DESCRICAO1: TStringField;
    CDS_COBRANCA3ID_PLANO: TIntegerField;
    Sds_CobrancaDT_PREVISAO_PGTO: TDateField;
    Sds_CobrancaDIAS_VENCIDO: TIntegerField;
    Sds_CobrancaN_OS: TStringField;
    Sds_CobrancaVLR_GRAFICA: TFMTBCDField;
    Sds_CobrancaVALOR_COMISAO: TFMTBCDField;
    Sds_CobrancaCOD_ENTRADA: TStringField;
    Sds_CobrancaFILTRO: TIntegerField;
    CDS_COBRANCATIPO: TStringField;
    CDS_COBRANCACHEK_BOX: TStringField;
    CDS_COBRANCANUM_NOTA: TIntegerField;
    CDS_COBRANCASERIE_NOTA: TStringField;
    CDS_COBRANCANOME_SACADO: TStringField;
    CDS_COBRANCAANO: TStringField;
    CDS_COBRANCAMES: TStringField;
    CDS_COBRANCATP_BAIXA: TStringField;
    CDS_COBRANCAID_CONTRATO: TIntegerField;
    CDS_COBRANCANOME_ARQ: TStringField;
    CDS_COBRANCACOBRADOR: TIntegerField;
    CDS_COBRANCACOMISSAO: TFMTBCDField;
    CDS_COBRANCADT_PREVISAO_PGTO: TDateField;
    CDS_COBRANCADIAS_VENCIDO: TIntegerField;
    CDS_COBRANCAN_OS: TStringField;
    CDS_COBRANCAVLR_GRAFICA: TFMTBCDField;
    CDS_COBRANCAVALOR_COMISAO: TFMTBCDField;
    CDS_COBRANCACOD_ENTRADA: TStringField;
    CDS_COBRANCAFILTRO: TIntegerField;
    SDS_TitulosCOBRADOR: TIntegerField;
    SDS_TitulosCOMISSAO: TFMTBCDField;
    SDS_TitulosDT_PREVISAO_PGTO: TDateField;
    SDS_TitulosDIAS_VENCIDO: TIntegerField;
    SDS_TitulosCOD_ENTRADA: TStringField;
    qryCobranca1COD_ENTRADA: TStringField;
    qryCobranca1ANO: TStringField;
    qryCobranca1MES: TStringField;
    qryCobranca1TP_BAIXA: TStringField;
    qryCobranca1NOME_ARQ: TStringField;
    qryCobranca1N_OS: TStringField;
    qryCobranca1VLR_GRAFICA: TFMTBCDField;
    qryCobranca1VALOR_COMISAO: TFMTBCDField;
    qryCobranca1FILTRO: TIntegerField;
    CDS_COBRANCA1COD_ENTRADA: TStringField;
    CDS_COBRANCA1ANO: TStringField;
    CDS_COBRANCA1MES: TStringField;
    CDS_COBRANCA1TP_BAIXA: TStringField;
    CDS_COBRANCA1NOME_ARQ: TStringField;
    CDS_COBRANCA1N_OS: TStringField;
    CDS_COBRANCA1VLR_GRAFICA: TFMTBCDField;
    CDS_COBRANCA1VALOR_COMISAO: TFMTBCDField;
    CDS_COBRANCA1FILTRO: TIntegerField;
    qryTitulosCODIGO: TIntegerField;
    qryTitulosCODIGO_CLIENTE: TIntegerField;
    qryTitulosDATA_COMPRA: TDateField;
    qryTitulosDATA_VENCIMENTO: TDateField;
    qryTitulosDATA_BAIXA: TDateField;
    qryTitulosHISTORICO: TStringField;
    qryTitulosUSUARIO_VENDA: TStringField;
    qryTitulosUSUARIO_BAIXA: TStringField;
    qryTitulosSITUACAO: TStringField;
    qryTitulosVALOR_COMPRA: TFMTBCDField;
    qryTitulosVALOR_JUROS: TFMTBCDField;
    qryTitulosVALOR_ACRESCIMO: TFMTBCDField;
    qryTitulosVALOR_DESCONTO: TFMTBCDField;
    qryTitulosVALOR_PAGAR: TFMTBCDField;
    qryTitulosVALOR_PAGO: TFMTBCDField;
    qryTitulosVALOR_TOTAL: TFMTBCDField;
    qryTitulosCODIGO_COMPRA: TIntegerField;
    qryTitulosPARCELA: TStringField;
    qryTitulosNUMBOLETO: TStringField;
    qryTitulosBANCO_PORTADOR: TIntegerField;
    qryTitulosREMESSA: TStringField;
    qryTitulosDATACREDITO: TDateField;
    qryTitulosID_PORTADOR: TIntegerField;
    qryTitulosENVIADO: TStringField;
    qryTitulosCOD_EMPRESA: TIntegerField;
    qryTitulosNUMBOLETO1: TIntegerField;
    qryTitulosCODIGOCEDENTE: TStringField;
    qryTitulosTIPO: TStringField;
    qryTitulosCHEK_BOX: TStringField;
    qryTitulosNUM_NOTA: TIntegerField;
    qryTitulosSERIE_NOTA: TStringField;
    qryTitulosNOME_SACADO: TStringField;
    qryTitulosANO: TStringField;
    qryTitulosMES: TStringField;
    qryTitulosTP_BAIXA: TStringField;
    qryTitulosID_CONTRATO: TIntegerField;
    qryTitulosNOME_ARQ: TStringField;
    qryTitulosCOBRADOR: TIntegerField;
    qryTitulosCOMISSAO: TFMTBCDField;
    qryTitulosDT_PREVISAO_PGTO: TDateField;
    qryTitulosDIAS_VENCIDO: TIntegerField;
    qryTitulosN_OS: TStringField;
    qryTitulosVLR_GRAFICA: TFMTBCDField;
    qryTitulosVALOR_COMISAO: TFMTBCDField;
    qryTitulosCOD_ENTRADA: TStringField;
    qryTitulosFILTRO: TIntegerField;
    cds_titulosCODIGO: TIntegerField;
    cds_titulosCODIGO_CLIENTE: TIntegerField;
    cds_titulosDATA_COMPRA: TDateField;
    cds_titulosDATA_VENCIMENTO: TDateField;
    cds_titulosDATA_BAIXA: TDateField;
    cds_titulosHISTORICO: TStringField;
    cds_titulosUSUARIO_VENDA: TStringField;
    cds_titulosUSUARIO_BAIXA: TStringField;
    cds_titulosSITUACAO: TStringField;
    cds_titulosVALOR_COMPRA: TFMTBCDField;
    cds_titulosVALOR_JUROS: TFMTBCDField;
    cds_titulosVALOR_ACRESCIMO: TFMTBCDField;
    cds_titulosVALOR_DESCONTO: TFMTBCDField;
    cds_titulosVALOR_PAGAR: TFMTBCDField;
    cds_titulosVALOR_PAGO: TFMTBCDField;
    cds_titulosVALOR_TOTAL: TFMTBCDField;
    cds_titulosCODIGO_COMPRA: TIntegerField;
    cds_titulosPARCELA: TStringField;
    cds_titulosNUMBOLETO: TStringField;
    cds_titulosBANCO_PORTADOR: TIntegerField;
    cds_titulosREMESSA: TStringField;
    cds_titulosDATACREDITO: TDateField;
    cds_titulosID_PORTADOR: TIntegerField;
    cds_titulosENVIADO: TStringField;
    cds_titulosCOD_EMPRESA: TIntegerField;
    cds_titulosNUMBOLETO1: TIntegerField;
    cds_titulosCODIGOCEDENTE: TStringField;
    cds_titulosTIPO: TStringField;
    cds_titulosCHEK_BOX: TStringField;
    cds_titulosNUM_NOTA: TIntegerField;
    cds_titulosSERIE_NOTA: TStringField;
    cds_titulosNOME_SACADO: TStringField;
    cds_titulosANO: TStringField;
    cds_titulosMES: TStringField;
    cds_titulosTP_BAIXA: TStringField;
    cds_titulosID_CONTRATO: TIntegerField;
    cds_titulosNOME_ARQ: TStringField;
    cds_titulosCOBRADOR: TIntegerField;
    cds_titulosCOMISSAO: TFMTBCDField;
    cds_titulosDT_PREVISAO_PGTO: TDateField;
    cds_titulosDIAS_VENCIDO: TIntegerField;
    cds_titulosN_OS: TStringField;
    cds_titulosVLR_GRAFICA: TFMTBCDField;
    cds_titulosVALOR_COMISAO: TFMTBCDField;
    cds_titulosCOD_ENTRADA: TStringField;
    cds_titulosFILTRO: TIntegerField;
    SQLD_CobrancaCOD_AVALISTA: TIntegerField;
    QryCobranca2COD_ENTRADA: TStringField;
    cds_cobranca2COD_ENTRADA: TStringField;
    qryCobranca1COD_AVALISTA: TIntegerField;
    qryCobranca1COD_FRETE: TIntegerField;
    CDS_COBRANCA1COD_AVALISTA: TIntegerField;
    CDS_COBRANCA1COD_FRETE: TIntegerField;
    Sds_CobrancaCOD_AVALISTA: TIntegerField;
    Sds_CobrancaCOD_FRETE: TIntegerField;
    CDS_COBRANCACOD_AVALISTA: TIntegerField;
    CDS_COBRANCACOD_FRETE: TIntegerField;
    qryTitulosCOD_AVALISTA: TIntegerField;
    qryTitulosCOD_FRETE: TIntegerField;
    qryTitulosCOD_CONV: TIntegerField;
    qryTitulosCOM_REGISTRO: TIntegerField;
    cds_titulosCOD_AVALISTA: TIntegerField;
    cds_titulosCOD_FRETE: TIntegerField;
    cds_titulosCOD_CONV: TIntegerField;
    cds_titulosCOM_REGISTRO: TIntegerField;
    SDS_TitulosANO: TStringField;
    SDS_TitulosMES: TStringField;
    SDS_TitulosTP_BAIXA: TStringField;
    SDS_TitulosNOME_ARQ: TStringField;
    SDS_TitulosN_OS: TStringField;
    SDS_TitulosVLR_GRAFICA: TFMTBCDField;
    SDS_TitulosVALOR_COMISAO: TFMTBCDField;
    SDS_TitulosFILTRO: TIntegerField;
    SDS_TitulosCOD_AVALISTA: TIntegerField;
    SDS_TitulosCOD_FRETE: TIntegerField;
    SDS_TitulosCOD_CONV: TIntegerField;
    SDS_TitulosCOM_REGISTRO: TIntegerField;
    qryCobranca1COD_CONV: TIntegerField;
    qryCobranca1COM_REGISTRO: TIntegerField;
    CDS_COBRANCA1COD_CONV: TIntegerField;
    CDS_COBRANCA1COM_REGISTRO: TIntegerField;
    qryCedentesPERC_JUROS: TFMTBCDField;
    qryCedentesPERC_MULTA: TFMTBCDField;
    ACBrBoleto: TACBrBoleto;
    ACBrMail1: TACBrMail;
    OpenDialog: TOpenDialog;
    SaveDialog: TSaveDialog;
    ACBrExtenso: TACBrExtenso;
    qryCBR_CONFIG: TFDQuery;
    qryCBR_CONFIGCODIGO_BOLETO: TIntegerField;
    qryCBR_CONFIGCOD_EMPRESA: TIntegerField;
    qryCBR_CONFIGDESCRICAO: TStringField;
    qryCBR_CONFIGBANCO_PORTADOR: TIntegerField;
    qryCBR_CONFIGQUANT_DIAS_PROTESTO: TSmallintField;
    qryCBR_CONFIGOBSERVACAO: TStringField;
    qryCBR_CONFIGLOCAL_PAGAMENTO: TStringField;
    qryCBR_CONFIGTIPO: TStringField;
    qryCBR_CONFIGNOMECEDENTE: TStringField;
    qryCBR_CONFIGCNPJCEDENTE: TStringField;
    qryCBR_CONFIGTIPOPESSOACEDENTE: TStringField;
    qryCBR_CONFIGCODIGOAGENCIA: TStringField;
    qryCBR_CONFIGDIGITOAGENCIA: TStringField;
    qryCBR_CONFIGNUMEROCONTA: TStringField;
    qryCBR_CONFIGDIGITOCONTA: TStringField;
    qryCBR_CONFIGCARTEIRA: TStringField;
    qryCBR_CONFIGVLRABATIMENTO: TFloatField;
    qryCBR_CONFIGVLRDESCONTO: TFloatField;
    qryCBR_CONFIGVLRDESPESACOBRANCA: TFloatField;
    qryCBR_CONFIGVLRIOF: TFloatField;
    qryCBR_CONFIGVLRMORAJUROS: TFloatField;
    qryCBR_CONFIGVLROUTRASDEPESAS: TFloatField;
    qryCBR_CONFIGVLROUTROSCREDITOS: TFloatField;
    qryCBR_CONFIGFLAG_GERAR_REMESSA: TStringField;
    qryCBR_CONFIGNOSSONUMERO: TStringField;
    qryCBR_CONFIGNUMERO_REMESSA: TIntegerField;
    qryCBR_CONFIGANO_REFERENCIA: TStringField;
    qryCBR_CONFIGPROTESTAR_AUTOMATICO: TStringField;
    qryCBR_CONFIGMODELO: TStringField;
    qryCBR_CONFIGUSERCAD: TStringField;
    qryCBR_CONFIGDATACAD: TDateField;
    qryCBR_CONFIGNOME_AGENCIA: TStringField;
    qryCBR_CONFIGCEDENTECODIGO: TStringField;
    qryCBR_CONFIGCEDENTECODIGODIGITO: TStringField;
    qryCBR_CONFIGCIDADE: TStringField;
    qryCBR_CONFIGENDERECO: TStringField;
    qryCBR_CONFIGUF: TStringField;
    qryCBR_CONFIGEMAIL: TStringField;
    qryCBR_CONFIGNUMERO: TIntegerField;
    qryCBR_CONFIGCEP: TStringField;
    qryCBR_CONFIGBAIRRO: TStringField;
    qryCBR_CONFIGCOMPLEMENTO: TStringField;
    qryCBR_CONFIGANO: TStringField;
    qryCBR_CONFIGTP_COBRANCA: TStringField;
    qryCBR_CONFIGLOGO: TBlobField;
    qryCBR_CONFIGPERC_JUROS: TFMTBCDField;
    qryCBR_CONFIGPERC_MULTA: TFMTBCDField;
    qryCBR_CONFIGCNAB: TStringField;
    qryCBR_CONFIGEMP_RAZAOSOCIAL: TStringField;
    qryCBR_CONFIGEMP_CNPJ: TStringField;
    qryCBR_CONFIGEMP_ENDERECO: TStringField;
    qryCBR_CONFIGEMP_COMPLEMENTO: TStringField;
    qryCBR_CONFIGEMP_BAIRRO: TStringField;
    qryCBR_CONFIGCIDADE_1: TStringField;
    qryCBR_CONFIGEMP_UF: TStringField;
    qryCBR_CONFIGEMP_CEP: TStringField;
    qryCBR_CONFIGEMP_TELEFONE: TStringField;
    qryCBR_CONFIGDIRRECEBE: TStringField;
    qryCBR_CONFIGDIRENVIA: TStringField;
    qryCedentesCNAB: TStringField;
    qryCedentesDIRRECEBE: TStringField;
    qryCedentesDIRENVIA: TStringField;
    qryCedentesESPECIE: TStringField;
    qryCedentesACEITE: TStringField;
    qryCBR_CONFIGESPECIE: TStringField;
    qryCBR_CONFIGACEITE: TStringField;
    qryCBR_CONFIGMODALIDADE: TStringField;
    tabCBR_TITULOS: TFDQuery;
    tabCBR_TITULOSCODIGO: TIntegerField;
    tabCBR_TITULOSDATA: TDateField;
    tabCBR_TITULOSFKCLIENTE: TIntegerField;
    tabCBR_TITULOSDOC: TStringField;
    tabCBR_TITULOSVALOR: TCurrencyField;
    tabCBR_TITULOSDTVENCIMENTO: TDateField;
    tabCBR_TITULOSHISTORICO: TStringField;
    tabCBR_TITULOSDATA_RECEBIMENTO: TDateField;
    tabCBR_TITULOSDESCONTO: TCurrencyField;
    tabCBR_TITULOSJUROS: TFMTBCDField;
    tabCBR_TITULOSVL_RESTANTE: TFMTBCDField;
    tabCBR_TITULOSSITUACAO: TStringField;
    tabCBR_TITULOSFKEMPRESA: TIntegerField;
    tabCBR_TITULOSFK_VENDA: TIntegerField;
    tabCBR_TITULOSVRECEBIDO: TCurrencyField;
    tabCBR_TITULOSFKCONTA: TIntegerField;
    tabCBR_TITULOSTIPO: TStringField;
    tabCBR_TITULOSNBOLETO: TIntegerField;
    tabCBR_TITULOSID_VENDEDOR: TIntegerField;
    tabCBR_TITULOSFLAG: TStringField;
    tabCBR_TITULOSFK_OS: TIntegerField;
    tabCBR_TITULOSBLOQUEADO: TStringField;
    tabCBR_TITULOSFK_USUARIO: TIntegerField;
    tabCBR_TITULOSCARTAO: TStringField;
    tabCBR_TITULOSFPG_VENDA: TIntegerField;
    tabCBR_TITULOSREMESSA: TStringField;
    tabCBR_TITULOSREMESSA_REENVIAR: TStringField;
    tabCBR_TITULOSREMESSA_DATA: TDateField;
    tabCBR_TITULOSREMESSA_ARQUIVO: TStringField;
    tabCBR_TITULOSREGISTRO_ID_CBR_RETORNO: TLargeintField;
    tabCBR_TITULOSREGISTRO_STATUS: TStringField;
    tabCBR_TITULOSREGISTRO_DATA: TSQLTimeStampField;
    tabCBR_TITULOSREGISTRO_ARQUIVO: TStringField;
    tabCBR_TITULOSRETORNO_ID_CBR_RETORNO: TIntegerField;
    tabCBR_TITULOSREGISTRO_HISTORICO: TStringField;
    tabCBR_TITULOSREGISTRO_SEM_REGISTRO: TStringField;
    tabCBR_TITULOSREGISTRO_LIMITE_PRAZO: TStringField;
    tabCBR_TITULOSRETORNO_HISTORICO: TStringField;
    tabCBR_TITULOSOBS: TStringField;
    tabCBR_TITULOSID_CBR_REMESSA_UUID: TStringField;
    tabCBR_TITULOSRETORNO_SEM_REGISTRO: TStringField;
    tabCBR_TITULOSRETORNO_LIMITE_PRAZO: TStringField;
    tabCBR_TITULOScalc_VlrTotal: TCurrencyField;
    qryCBR_CONFIGCOD_PLANO: TIntegerField;
    qryCBR_CONFIGCODIGO: TIntegerField;
    qryCBR_CONFIGFEBRABAN: TStringField;
    qryCBR_CONFIGBANCO: TStringField;
    qryCBR_CONFIGTITULAR: TStringField;
    qryCBR_CONFIGAGENCIA: TStringField;
    qryCBR_CONFIGCONTA: TStringField;
    qryCBR_CONFIGDIGITO: TStringField;
    qryCBR_CONFIGTIPO_1: TStringField;
    qryCBR_CONFIGUSERCAD_1: TStringField;
    qryCBR_CONFIGDATACAD_1: TDateField;
    sds_cedentesPERC_JUROS: TFMTBCDField;
    sds_cedentesPERC_MULTA: TFMTBCDField;
    sds_cedentesCNAB: TStringField;
    sds_cedentesDIRRECEBE: TStringField;
    sds_cedentesDIRENVIA: TStringField;
    sds_cedentesESPECIE: TStringField;
    sds_cedentesACEITE: TStringField;
    sds_cedentesMODALIDADE: TStringField;
    sds_cedentesVERSAO: TStringField;
    sds_cedentesVERSAO_LOTE: TStringField;
    SDS_TitulosRECEBIVEL: TIntegerField;
    SDS_TitulosID_CT_PARCELA: TIntegerField;
    SDS_TitulosJUROS_POSTERGADOS: TFMTBCDField;
    SDS_TitulosID_CBR_REMESSA_UUID: TStringField;
    Sds_CobrancaCOD_CONV: TIntegerField;
    Sds_CobrancaCOM_REGISTRO: TIntegerField;
    Sds_CobrancaRECEBIVEL: TIntegerField;
    Sds_CobrancaID_CT_PARCELA: TIntegerField;
    Sds_CobrancaJUROS_POSTERGADOS: TFMTBCDField;
    Sds_CobrancaID_CBR_REMESSA_UUID: TStringField;
    qryCBR_CONFIGVERSAO: TStringField;
    qryCBR_CONFIGVERSAO_LOTE: TStringField;
    qryCBR_CONFIGCONVENIO: TStringField;
    ACBrBoletoFCFR1: TACBrBoletoFCFR;
    procedure DataModuleCreate(Sender: TObject);
    procedure SQLCBeforeConnect(Sender: TObject);
    procedure ConfigurarBoleta;
//   procedure EnviarEmal(email, Cliente: string);
  private
    { Private declarations }
      A: Real;
  public
    { Public declarations }

  end;

var
  DMCOB: TDMCOB;

implementation

uses ModulodeDados;



{$R *.dfm}

procedure TDMCOB.ConfigurarBoleta;
  function StrToTipoCobranca(const AValor: String): TACBrTipoCobranca;
  begin
    Result := TACBrTipoCobranca
      (GetEnumValue(TypeInfo(TACBrTipoCobranca), AValor))
  end;

begin
  try
    qryCBR_CONFIG.Close;
    qryCBR_CONFIG.Params[0].Value := iemp;
    qryCBR_CONFIG.Params[1].value := cod_cob;
    qryCBR_CONFIG.Open;
    qryCBR_CONFIG.FetchAll;

    if qryCBR_CONFIG.IsEmpty then
      raise Exception.Create
        ('Configuração da cobrança não foi efetuada, favor corrigir.');

    // dados da empresa cedente

    if qryCBR_CONFIGCNAB.Value = 'CNAB 400' then
      ACBrBoleto.LayoutRemessa := c400
    else
      ACBrBoleto.LayoutRemessa := c240;


    ACBrBoleto.Banco.TipoCobranca          := StrToTipoCobranca(qryCBR_CONFIG.FieldByName('TIPO').AsString);     //banco
    ACBrBoleto.Cedente.Nome                := qryCBR_CONFIG.FieldByName('EMP_RAZAOSOCIAL').AsString;
    ACBrBoleto.Cedente.CNPJCPF             := qryCBR_CONFIG.FieldByName('EMP_CNPJ').AsString;
    ACBrBoleto.Cedente.CodigoCedente       := qryCBR_CONFIG.FieldByName('CEDENTECODIGO').AsString.Trim;
    ACBrBoleto.Cedente.Convenio            := qryCBR_CONFIG.FieldByName('CONVENIO').AsString.Trim;
    ACBrBoleto.Cedente.Modalidade          := qryCBR_CONFIG.FieldByName('MODALIDADE').AsString.Trim;  //01 - com registro - 02 - sem registro 03 - com garantia caucionada
    ACBrBoleto.Cedente.Agencia             := qryCBR_CONFIG.FieldByName('CODIGOAGENCIA').AsString.Trim;
    ACBrBoleto.Cedente.AgenciaDigito       := qryCBR_CONFIG.FieldByName('DIGITOAGENCIA').AsString.Trim;
    ACBrBoleto.Cedente.DigitoVerificadorAgenciaConta  := qryCBR_CONFIG.FieldByName('DIGITOAGENCIA').AsString.Trim;
    ACBrBoleto.Cedente.Conta               := qryCBR_CONFIG.FieldByName('NUMEROCONTA').AsString.Trim;
    ACBrBoleto.Cedente.ContaDigito         := qryCBR_CONFIG.FieldByName('DIGITOCONTA').AsString.Trim;
    ACBrBoleto.Cedente.Logradouro          := qryCBR_CONFIG.FieldByName('EMP_ENDERECO').AsString;
    ACBrBoleto.Cedente.Complemento         := qryCBR_CONFIG.FieldByName('EMP_COMPLEMENTO').AsString;
    ACBrBoleto.Cedente.Bairro              := qryCBR_CONFIG.FieldByName('EMP_BAIRRO').AsString;
    ACBrBoleto.Cedente.Cidade              := qryCBR_CONFIG.FieldByName('CIDADE').AsString;
    ACBrBoleto.Cedente.CEP                 := qryCBR_CONFIG.FieldByName('EMP_CEP').AsString;
    ACBrBoleto.Cedente.UF                  := qryCBR_CONFIG.FieldByName('EMP_UF').AsString;
    ACBrBoleto.Cedente.Telefone            := qryCBR_CONFIG.FieldByName('EMP_TELEFONE').AsString;
    ACBrBoleto.DirArqRetorno               := qryCBR_CONFIG.FieldByName('DIRRECEBE').AsString.Trim;
    ACBrBoleto.DirArqRemessa               := qryCBR_CONFIG.FieldByName('DIRENVIA').AsString.Trim;
    ACBrBoleto.Banco.TamanhoMaximoNossoNum := 7;

    if qryCBR_CONFIGCNAB.Value = 'CNAB 240' then
    begin
    ACBrBoleto.Banco.LayoutVersaoArquivo   := StrToIntDef(qryCBR_CONFIG.FieldByName('VERSAO').AsString,0);
    ACBrBoleto.Banco.LayoutVersaoLote      := StrToIntDef(qryCBR_CONFIG.FieldByName('VERSAO_LOTE').AsString,0);
    end;




  //  ACBrBoleto. :=  TACBrTipoCarteira(qryCBR_CONFIG.FieldByName('CARTEIRA').AsString, Integer(TipoCarteira));

    {if IniBoletos.SectionExists('WEBSERVICE') then
      begin
        CedenteWS.ClientID                  := IniBoletos.ReadString(CWebService,'ClientID', '');
        CedenteWS.ClientSecret              := IniBoletos.ReadString(CWebService,'ClientSecret', '');
        CedenteWS.KeyUser                   := IniBoletos.ReadString(CWebService,'KeyUser', '');
        CedenteWS.IndicadorPix              := IniBoletos.ReadBool(CWebService,'IndicadorPix', false);
        CedenteWS.Scope                     := IniBoletos.ReadString(CWebService,'Scope', '');
        Configuracoes.WebService.Ambiente   := TpcnTipoAmbiente(IniBoletos.ReadInteger(CWebService,'Ambiente', Integer(Configuracoes.WebService.Ambiente)));
        Configuracoes.WebService.SSLHttpLib := TSSLHttpLib(IniBoletos.ReadInteger(CWebService,'SSLHttpLib', Integer(Configuracoes.WebService.SSLHttpLib)));
        Result := True;
      end; }

    ACBrBoletoFCFR1.DirLogo := ExtractFilePath(Application.ExeName) + 'Boleto\Logos';
  finally
    // qryCBR_CONFIG.Close;
  end;

  if not DirectoryExists(ACBrBoleto.DirArqRetorno) then
    raise Exception.Create('Diretório de Retorno não existe, favor verificar!' +
      sLineBreak + sLineBreak + ACBrBoleto.DirArqRetorno);

  if not DirectoryExists(ACBrBoleto.DirArqRemessa) then
    raise Exception.Create('Diretório de Remessa não existe, favor verificar!' +
      sLineBreak + sLineBreak + ACBrBoleto.DirArqRemessa);
end;

{procedure TDMCOB.EnviarEmal(email, Cliente: string);
var
  mensagem: Tstrings;
  para: string;
begin

  if Trim(Dados.qryEmpresaEMAIL.AsString) = '' then
    exit;

  try
    mensagem := TstringList.Create;
    mensagem.Add('SEGUE EM ANEXO BOLETO DE COBRANÇA');

    FEmail.GetEmail;

    ACBrMail1.FromName := Cliente;
    ACBrMail1.Host := FEmail.servidor;
    ACBrMail1.Port := FEmail.porta;
    ACBrMail1.AddAddress(LowerCase(FEmail.usuario), '');
    ACBrMail1.Username := LowerCase(FEmail.usuario);
    ACBrMail1.From := LowerCase(FEmail.usuario);
    ACBrMail1.Password := FEmail.Senha;

    ACBrMail1.DefaultCharset := TMailCharset(27);
    ACBrMail1.IDECharset := TMailCharset(15);

    ACBrMail1.IsHTML := false;

    ACBrMail1.SetSSL := false;
    ACBrMail1.SetTLS := false;

    if FEmail.SSL then
      ACBrMail1.SetSSL := true;

    if FEmail.TLS then
      ACBrMail1.SetTLS := true;

    ACBrMail1.ReadingConfirmation := true;
    ACBrMail1.UseThread := false;

    if (email = '') then
      para := LowerCase(Dados.qryEmpresaEMAIL.Value)
    else
      para := LowerCase(email);

    ACBrBoleto1.EnviarEmail(para, 'Boleto -' + Cliente, mensagem, true
      // Enviar PDF junto
      , nil // Lista com emails que serÃ£o enviado cÃ³pias - TStrings
      , nil); // Lista de anexos - TStrings

  finally
    mensagem.Free;
  end;
end;     }

procedure TDMCOB.DataModuleCreate(Sender: TObject);
var
  I: Integer;
begin
for I := 0 to Pred(Self.ComponentCount) do
 begin
   if Self.Components[I] is TSimpleDataSet then
   begin
     (Self.Components[I] as TSimpleDataSet).Connection:= DM.SQLC;
   end
   else
   if Self.Components[I] is TSQLQuery then
   begin
      (Self.Components[I] as TSQLQuery).SQLConnection:= DM.SQLC;
   end;
 end;
end;

procedure TDMCOB.SQLCBeforeConnect(Sender: TObject);
//var
//Arquivo: TIniFile{uses IniFiles};
begin
{ Try
     Arquivo:= TIniFile.Create(ExtractFilePath(Application.ExeName)+'siace.ini');
     with DMCOB.SQLC do
     begin
       Params.Values['DATABASE'] := Arquivo.ReadString('DADOS','DATABASE','');
       Params.Values['USERNAME'] := Arquivo.ReadString('DADOS','USERNAME','');
       Params.Values['PASSWORD'] := Arquivo.ReadString('DADOS','PASSWORD','');
       Arquivo.Free
     end;
  Except
    ShowMessage('Não foi possivel conectar! Nenhum servidor disponível...');

  End;}   


end;

end.
