unit DMOS1;

interface

uses
  SysUtils, Classes, DB, DBClient, SimpleDS, SqlExpr, FMTBcd,
  Provider, Data.DBXFirebird;

type
  TDMOS = class(TDataModule)
    SDS_TipoBens: TSimpleDataSet;
    Dts_TipoBens: TDataSource;
    SDS_TipoBensID_OS_EQUIPAMENTO_TIPO: TIntegerField;
    SDS_TipoBensTIPO: TStringField;
    SDS_TipoBensFLAG_CHECKLIST_ACESSORIOS: TStringField;
    SDS_TipoBensFLAG_CHECKLIST_DEFEITOS: TStringField;
    SDS_TipoBensUSERCAD: TStringField;
    SDS_TipoBensDATACAD: TDateField;
    SDS_OSMarcas: TSimpleDataSet;
    SDS_OSMarcasID_OS_EQUIPAMENTO_MARCAS: TIntegerField;
    SDS_OSMarcasMARCA: TStringField;
    DTS_OSMarcas: TDataSource;
    SDS_OSMarcasUSERCAD: TStringField;
    SDS_OSMarcasDATACAD: TDateField;
    SDS_OScor: TSimpleDataSet;
    SDS_OScorID_OS_EQUIPAMENTO_COR: TIntegerField;
    SDS_OScorCOR: TStringField;
    SDS_OScorUSERCAD: TStringField;
    SDS_OScorDATACAD: TDateField;
    DTS_OSCOR: TDataSource;
    Sds_localizacao: TSimpleDataSet;
    Dts_localizacao: TDataSource;
    Sds_localizacaoID_OS_LOCALEQUIPAMENTO: TIntegerField;
    Sds_localizacaoLOCAL: TStringField;
    Sds_localizacaoUSERCAD: TStringField;
    Sds_localizacaoDATACAD: TDateField;
    Sds_bem: TSimpleDataSet;
    Dts_bem: TDataSource;
    Sds_bemID_OS_EQUIPAMENTOS: TIntegerField;
    Sds_bemID_OS_EQUIPAMENTO_TIPO: TIntegerField;
    Sds_bemID_OS_EQUIPAMENTO_MARCA: TIntegerField;
    Sds_bemMODELO: TStringField;
    Sds_bemUSERCAD: TStringField;
    Sds_bemDATACAD: TDateField;
    SDS_TPatendimento: TSimpleDataSet;
    DTS_TPAtendimento: TDataSource;
    SDS_TPatendimentoID_OS_TIPO: TIntegerField;
    SDS_TPatendimentoTIPOATENDIMENTO: TStringField;
    SDS_TPatendimentoFLAGEXTERNA: TStringField;
    SDS_TPatendimentoUSERCAD: TStringField;
    SDS_TPatendimentoDATACAD: TDateField;
    Sds_Prioridade: TSimpleDataSet;
    Dts_Prioridade: TDataSource;
    Sds_status: TSimpleDataSet;
    Dts_status: TDataSource;
    Sds_PrioridadeID_OS_PRIORIDADE: TIntegerField;
    Sds_PrioridadePRIORIDADE: TStringField;
    Sds_PrioridadeUSERCAD: TStringField;
    Sds_PrioridadeDATACAD: TDateField;
    Sds_statusID_OS_STATUS: TIntegerField;
    Sds_statusSTATUS: TStringField;
    Sds_statusUSERCAD: TStringField;
    Sds_statusDATACAD: TDateField;
    SDS_OS: TSimpleDataSet;
    SPC_OS: TSQLStoredProc;
    DTS_OS: TDataSource;
    SDS_OSID_OS_ORDEMSERVICO: TIntegerField;
    SDS_OSID_EMPRESA: TIntegerField;
    SDS_OSID_OS_PRIORIDADE: TIntegerField;
    SDS_OSID_OS_TIPOATENDIMENTO: TIntegerField;
    SDS_OSID_OS_STATUS: TIntegerField;
    SDS_OSID_CLIENTE: TIntegerField;
    SDS_OSID_OS_EQUIPAMENTO: TIntegerField;
    SDS_OSID_OS_EQUIPAMENTO_COR: TIntegerField;
    SDS_OSID_OS_EQUIP_LOCAL: TIntegerField;
    SDS_OSID_TECNICORESPONSAVEL: TIntegerField;
    SDS_OSIDENTIFICADOR: TStringField;
    SDS_OSEQUIPAMENTO_NSERIE: TStringField;
    SDS_OSNUMERO_OS: TIntegerField;
    SDS_OSNOMECONTATO: TStringField;
    SDS_OSFLAGEXTERNA: TStringField;
    SDS_OSDATA_ENTRADA: TDateField;
    SDS_OSHORA_ENTRADA: TTimeField;
    SDS_OSDATA_SOLUCAO: TDateField;
    SDS_OSHORA_SOLUCAO: TTimeField;
    SDS_OSCAMPO_DATAAGENDA: TDateField;
    SDS_OSCAMPO_HORAAGENDA: TTimeField;
    SDS_OSCAMPO_DATACHEGADA: TDateField;
    SDS_OSCAMPO_HORACHEGADA: TTimeField;
    SDS_OSCAMPO_DATASAIDA: TDateField;
    SDS_OSCAMPO_HORASAIDA: TTimeField;
    SDS_OSCAMPO_DATARETORNO: TDateField;
    SDS_OSCAMPO_HORARETORNO: TTimeField;
    SDS_OSCONSUMIDOR_NOME: TStringField;
    SDS_OSCONSUMIDOR_ENDERECO: TStringField;
    SDS_OSCONSUMIDOR_CPFCNPJ: TStringField;
    SDS_OSCONSUMIDOR_TELEFONE: TStringField;
    SDS_OSPRAZO_DATACONCLUSAO: TDateField;
    SDS_OSPRAZO_HORACONCLUSAO: TTimeField;
    SDS_OSMODELO: TStringField;
    SDS_OSOBS: TStringField;
    SDS_OSID_VENDA: TIntegerField;
    SDS_OSDATA_ALTERACAO: TSQLTimeStampField;
    SDS_OSOCORRENCIA: TStringField;
    SDS_OSOBSEQUIPAMENTO: TStringField;
    SDS_OSSOLUCAO: TStringField;
    SDS_OSREVENDEDOR: TStringField;
    SDS_OSMODALIDADE: TStringField;
    SDS_OSGARANTIA: TStringField;
    SDS_OSLACRE: TStringField;
    SDS_OSGARANTIA_CAMPO1: TStringField;
    SDS_OSDATA_PROXIMAREVISAO: TDateField;
    SDS_OSCONSUMIDOR_RGINSCR: TStringField;
    SDS_OSHORA_INICIO_ATEND: TTimeField;
    SDS_OSHORA_FIM_ATEND: TTimeField;
    SDS_OSUSERCAD: TStringField;
    SDS_OSDATACAD: TDateField;
    SDS_OSID_USUARIO: TIntegerField;
    sds_clientes: TSimpleDataSet;
    dts_clientes: TDataSource;
    sds_clientesCODIGO: TIntegerField;
    sds_clientesNOME_RS: TStringField;
    sds_clientesENDERECO: TStringField;
    sds_clientesCIDADE: TStringField;
    sds_clientesUF: TStringField;
    sds_clientesCEP: TStringField;
    sds_clientesTELEFONE: TStringField;
    sds_clientesTELEFONE2: TStringField;
    sds_clientesEMAIL: TStringField;
    sds_clientesNASCIMENTO_IA: TDateField;
    sds_clientesSEXO: TStringField;
    sds_clientesFOTO_LOGOMARCA: TBlobField;
    sds_clientesBAIRRO: TStringField;
    sds_clientesRG_IE: TStringField;
    sds_clientesFAX: TStringField;
    sds_clientesCELULAR: TStringField;
    sds_clientesUSERCAD: TStringField;
    sds_clientesDATACAD: TDateField;
    sds_clientesCPF_CNPJ: TStringField;
    sds_clientesOBSERVACOES: TBlobField;
    sds_clientesCREDIARIO: TStringField;
    sds_clientesESTADOCIVIL: TStringField;
    sds_clientesRESIDENCIA_SEDE: TStringField;
    sds_clientesPAI: TStringField;
    sds_clientesMAE: TStringField;
    sds_clientesNOME_CONJUGE: TStringField;
    sds_clientesCPF_CONJUGE: TStringField;
    sds_clientesNASCIMENTO_CONJUGE: TDateField;
    sds_clientesTRABALHO_CONJUGE: TStringField;
    sds_clientesPROFISSAO_CONJUGE: TStringField;
    sds_clientesLOCALTRABALHO: TStringField;
    sds_clientesPROFISSAO_RA: TStringField;
    sds_clientesTELEFONE_TRABALHO: TStringField;
    sds_clientesFAX_TRABALHO: TStringField;
    sds_clientesOBSERVACOES_TRABALHO: TBlobField;
    sds_clientesBANCO: TStringField;
    sds_clientesNOME_AGENCIA: TStringField;
    sds_clientesNUMERO_AGENCIA: TStringField;
    sds_clientesCONTA_CORRENTE: TIntegerField;
    sds_clientesNOME1_REFERENCIA: TStringField;
    sds_clientesNOME2_REFERENCIA: TStringField;
    sds_clientesTELEFONE1_REFERENCIA: TStringField;
    sds_clientesTELEFONE2_REFERENCIA: TStringField;
    sds_clientesBANCO_REFERENCIA: TStringField;
    sds_clientesAPELIDO: TStringField;
    sds_clientesTIPO: TStringField;
    sds_clientesOBSERVACOES_COMERCIAIS: TBlobField;
    sds_clientesOBSERVACOES_BANCO: TBlobField;
    sds_clientesPG_CREDIARIO: TStringField;
    sds_clientesPG_CHEQUE: TStringField;
    sds_clientesPG_FINANCEIRA: TStringField;
    sds_clientesREMUNERACAO: TFMTBCDField;
    sds_clientesNUMERO: TStringField;
    sds_clientesCOMPLEMENTO: TStringField;
    sds_clientesCOD_EMPRESA: TIntegerField;
    sds_clientesORGAO_EMISSOR: TStringField;
    sds_clientesDATA_EMISSAO_RG: TDateField;
    sds_clientesNATURALIDADE: TStringField;
    sds_clientesNATURALIDADE_UF: TStringField;
    sds_clientesCOD_CIDADE: TIntegerField;
    sds_clientesCOD_BAIRRO: TIntegerField;
    sds_clientesDATA_ALTERACAO: TDateField;
    sds_clientesCOD_ZONA: TIntegerField;
    sds_clientesPONTO_REFERENCIA: TStringField;
    sds_clientesATIVO: TStringField;
    sds_clientesCONTATO1: TStringField;
    sds_clientesCONTATO2: TStringField;
    sds_clientesCX_POSTAL: TStringField;
    sds_clientesVALOR_ALUGUEL: TFMTBCDField;
    sds_clientesTEMPO_RESIDENCIA: TStringField;
    sds_clientesNUMERO_DEPENDENTES: TIntegerField;
    sds_clientesENDERECO_REFERENCIA1: TStringField;
    sds_clientesENDERECO_REFERENCIA2: TStringField;
    sds_clientesDATA_ADMISSAO_REFERENCIA1: TDateField;
    sds_clientesDATA_ADMISSAO_REFERENCIA2: TDateField;
    sds_clientesRG_CONJUGUE: TStringField;
    sds_clientesRENDA_CONJUGUE: TFMTBCDField;
    sds_clientesDATA_ADMINSSAO_CONJUGUE: TDateField;
    sds_clientesFONE_CONJUGUE: TStringField;
    sds_clientesENDERECO_COBRANCA: TStringField;
    sds_clientesCEP_COBRANCA: TStringField;
    sds_clientesCOD_CIDADE_COBRANCA: TIntegerField;
    sds_clientesCX_POSTAL_COBRANCA: TStringField;
    sds_clientesLIMITE_DE_CREDITO: TFMTBCDField;
    sds_clientesINSC_MUNICIPAL: TStringField;
    sds_clientesPRODUTOR_RURAL: TStringField;
    sds_clientesINSC_PRODUTOR_RURAL: TStringField;
    sds_clientesCOD_BAIRRO_COBRANCA: TIntegerField;
    sds_clientesCIDADE_COBRANCA: TStringField;
    sds_clientesBAIRRO_COBRANCA: TStringField;
    sds_clientesUF_COBRANCA: TStringField;
    DTS_REL_OS: TDataSource;
    DTS_OS_PRODUTO: TDataSource;
    SDS_OS_PRODUTO: TSimpleDataSet;
    SDS_OS_PRODUTOID_OS_PRODUTOS_SERVICOS: TIntegerField;
    SDS_OS_PRODUTOID_OS_ORDEMSERVICO: TIntegerField;
    SDS_OS_PRODUTOID_OS_TECNICO: TIntegerField;
    SDS_OS_PRODUTOCOD_PRODUTO: TIntegerField;
    SDS_OS_PRODUTOCODIGO_BARRAS: TStringField;
    SDS_OS_PRODUTOVALOR_UNITARIO: TFloatField;
    SDS_OS_PRODUTOQUANTIDADE: TFloatField;
    SDS_OS_PRODUTOPERC_DESCONTO: TFloatField;
    SDS_OS_PRODUTOVLRDESCONTO: TFloatField;
    SDS_OS_PRODUTOVALOR_TOTAL: TFloatField;
    SDS_OS_PRODUTODESC_UNIDADE: TStringField;
    SDS_OS_PRODUTODTFIMPROMVAREJO: TDateField;
    SDS_OS_PRODUTODTINICIOPROMVAREJO: TDateField;
    SDS_OS_PRODUTOVALGRAMASAIDA: TFloatField;
    SDS_OS_PRODUTOESTAPROMOCAOVAREJO: TStringField;
    SDS_OS_PRODUTOEMBALAGEMSAIDA: TStringField;
    SDS_OS_PRODUTOPRECO_ATUAL_MANTIDO: TFloatField;
    SDS_OS_PRODUTODESCRICAO: TStringField;
    SDS_OS_PRODUTOPROD_SERV: TStringField;
    SDS_OS_PRODUTOSIT_TRIBUTARIA: TStringField;
    SDS_OS_PRODUTOFRACAO: TIntegerField;
    SDS_OS_PRODUTOCOD_NCM: TStringField;
    SDS_REL_PRODUTO: TSimpleDataSet;
    DTS_REL_PRODUTO: TDataSource;
    SDS_OSSITUACAO: TStringField;
    CDS_OS: TClientDataSet;
    DSP_OS: TDataSetProvider;
    DTS_OS1: TDataSource;
    QRY_OS: TSQLQuery;
    SDS_PRODUTOS: TSimpleDataSet;
    DTS_PRODUTOS: TDataSource;
    QRY_OSID_OS_ORDEMSERVICO: TIntegerField;
    QRY_OSID_EMPRESA: TIntegerField;
    QRY_OSID_OS_PRIORIDADE: TIntegerField;
    QRY_OSID_OS_TIPOATENDIMENTO: TIntegerField;
    QRY_OSID_OS_STATUS: TIntegerField;
    QRY_OSID_CLIENTE: TIntegerField;
    QRY_OSID_OS_EQUIPAMENTO: TIntegerField;
    QRY_OSID_OS_EQUIPAMENTO_COR: TIntegerField;
    QRY_OSID_OS_EQUIP_LOCAL: TIntegerField;
    QRY_OSID_TECNICORESPONSAVEL: TIntegerField;
    QRY_OSID_USUARIO: TIntegerField;
    QRY_OSSITUACAO: TStringField;
    QRY_OSIDENTIFICADOR: TStringField;
    QRY_OSEQUIPAMENTO_NSERIE: TStringField;
    QRY_OSNUMERO_OS: TIntegerField;
    QRY_OSNOMECONTATO: TStringField;
    QRY_OSFLAGEXTERNA: TStringField;
    QRY_OSDATA_ENTRADA: TDateField;
    QRY_OSHORA_ENTRADA: TTimeField;
    QRY_OSDATA_SOLUCAO: TDateField;
    QRY_OSHORA_SOLUCAO: TTimeField;
    QRY_OSCAMPO_DATAAGENDA: TDateField;
    QRY_OSCAMPO_HORAAGENDA: TTimeField;
    QRY_OSCAMPO_DATACHEGADA: TDateField;
    QRY_OSCAMPO_HORACHEGADA: TTimeField;
    QRY_OSCAMPO_DATASAIDA: TDateField;
    QRY_OSCAMPO_HORASAIDA: TTimeField;
    QRY_OSCAMPO_DATARETORNO: TDateField;
    QRY_OSCAMPO_HORARETORNO: TTimeField;
    QRY_OSCONSUMIDOR_NOME: TStringField;
    QRY_OSCONSUMIDOR_ENDERECO: TStringField;
    QRY_OSCONSUMIDOR_CPFCNPJ: TStringField;
    QRY_OSCONSUMIDOR_TELEFONE: TStringField;
    QRY_OSPRAZO_DATACONCLUSAO: TDateField;
    QRY_OSPRAZO_HORACONCLUSAO: TTimeField;
    QRY_OSMODELO: TStringField;
    QRY_OSOBS: TStringField;
    QRY_OSID_VENDA: TIntegerField;
    QRY_OSDATA_ALTERACAO: TSQLTimeStampField;
    QRY_OSOCORRENCIA: TStringField;
    QRY_OSOBSEQUIPAMENTO: TStringField;
    QRY_OSSOLUCAO: TStringField;
    QRY_OSREVENDEDOR: TStringField;
    QRY_OSMODALIDADE: TStringField;
    QRY_OSGARANTIA: TStringField;
    QRY_OSLACRE: TStringField;
    QRY_OSGARANTIA_CAMPO1: TStringField;
    QRY_OSDATA_PROXIMAREVISAO: TDateField;
    QRY_OSCONSUMIDOR_RGINSCR: TStringField;
    QRY_OSHORA_INICIO_ATEND: TTimeField;
    QRY_OSHORA_FIM_ATEND: TTimeField;
    QRY_OSUSERCAD: TStringField;
    QRY_OSDATACAD: TDateField;
    CDS_OSID_OS_ORDEMSERVICO: TIntegerField;
    CDS_OSID_EMPRESA: TIntegerField;
    CDS_OSID_OS_PRIORIDADE: TIntegerField;
    CDS_OSID_OS_TIPOATENDIMENTO: TIntegerField;
    CDS_OSID_OS_STATUS: TIntegerField;
    CDS_OSID_CLIENTE: TIntegerField;
    CDS_OSID_OS_EQUIPAMENTO: TIntegerField;
    CDS_OSID_OS_EQUIPAMENTO_COR: TIntegerField;
    CDS_OSID_OS_EQUIP_LOCAL: TIntegerField;
    CDS_OSID_TECNICORESPONSAVEL: TIntegerField;
    CDS_OSID_USUARIO: TIntegerField;
    CDS_OSSITUACAO: TStringField;
    CDS_OSIDENTIFICADOR: TStringField;
    CDS_OSEQUIPAMENTO_NSERIE: TStringField;
    CDS_OSNUMERO_OS: TIntegerField;
    CDS_OSNOMECONTATO: TStringField;
    CDS_OSFLAGEXTERNA: TStringField;
    CDS_OSDATA_ENTRADA: TDateField;
    CDS_OSHORA_ENTRADA: TTimeField;
    CDS_OSDATA_SOLUCAO: TDateField;
    CDS_OSHORA_SOLUCAO: TTimeField;
    CDS_OSCAMPO_DATAAGENDA: TDateField;
    CDS_OSCAMPO_HORAAGENDA: TTimeField;
    CDS_OSCAMPO_DATACHEGADA: TDateField;
    CDS_OSCAMPO_HORACHEGADA: TTimeField;
    CDS_OSCAMPO_DATASAIDA: TDateField;
    CDS_OSCAMPO_HORASAIDA: TTimeField;
    CDS_OSCAMPO_DATARETORNO: TDateField;
    CDS_OSCAMPO_HORARETORNO: TTimeField;
    CDS_OSCONSUMIDOR_NOME: TStringField;
    CDS_OSCONSUMIDOR_ENDERECO: TStringField;
    CDS_OSCONSUMIDOR_CPFCNPJ: TStringField;
    CDS_OSCONSUMIDOR_TELEFONE: TStringField;
    CDS_OSPRAZO_DATACONCLUSAO: TDateField;
    CDS_OSPRAZO_HORACONCLUSAO: TTimeField;
    CDS_OSMODELO: TStringField;
    CDS_OSOBS: TStringField;
    CDS_OSID_VENDA: TIntegerField;
    CDS_OSDATA_ALTERACAO: TSQLTimeStampField;
    CDS_OSOCORRENCIA: TStringField;
    CDS_OSOBSEQUIPAMENTO: TStringField;
    CDS_OSSOLUCAO: TStringField;
    CDS_OSREVENDEDOR: TStringField;
    CDS_OSMODALIDADE: TStringField;
    CDS_OSGARANTIA: TStringField;
    CDS_OSLACRE: TStringField;
    CDS_OSGARANTIA_CAMPO1: TStringField;
    CDS_OSDATA_PROXIMAREVISAO: TDateField;
    CDS_OSCONSUMIDOR_RGINSCR: TStringField;
    CDS_OSHORA_INICIO_ATEND: TTimeField;
    CDS_OSHORA_FIM_ATEND: TTimeField;
    CDS_OSUSERCAD: TStringField;
    CDS_OSDATACAD: TDateField;
    Qry_rel_os: TSQLQuery;
    dsp_rel_os: TDataSetProvider;
    cds_rel_os: TClientDataSet;
    Qry_rel_osID_OS_ORDEMSERVICO: TIntegerField;
    Qry_rel_osID_EMPRESA: TIntegerField;
    Qry_rel_osID_OS_PRIORIDADE: TIntegerField;
    Qry_rel_osID_OS_TIPOATENDIMENTO: TIntegerField;
    Qry_rel_osID_OS_STATUS: TIntegerField;
    Qry_rel_osID_CLIENTE: TIntegerField;
    Qry_rel_osID_OS_EQUIPAMENTO: TIntegerField;
    Qry_rel_osID_OS_EQUIPAMENTO_COR: TIntegerField;
    Qry_rel_osID_OS_EQUIP_LOCAL: TIntegerField;
    Qry_rel_osID_TECNICORESPONSAVEL: TIntegerField;
    Qry_rel_osID_USUARIO: TIntegerField;
    Qry_rel_osSITUACAO: TStringField;
    Qry_rel_osIDENTIFICADOR: TStringField;
    Qry_rel_osEQUIPAMENTO_NSERIE: TStringField;
    Qry_rel_osNUMERO_OS: TIntegerField;
    Qry_rel_osNOMECONTATO: TStringField;
    Qry_rel_osFLAGEXTERNA: TStringField;
    Qry_rel_osDATA_ENTRADA: TDateField;
    Qry_rel_osHORA_ENTRADA: TTimeField;
    Qry_rel_osDATA_SOLUCAO: TDateField;
    Qry_rel_osHORA_SOLUCAO: TTimeField;
    Qry_rel_osCAMPO_DATAAGENDA: TDateField;
    Qry_rel_osCAMPO_HORAAGENDA: TTimeField;
    Qry_rel_osCAMPO_DATACHEGADA: TDateField;
    Qry_rel_osCAMPO_HORACHEGADA: TTimeField;
    Qry_rel_osCAMPO_DATASAIDA: TDateField;
    Qry_rel_osCAMPO_HORASAIDA: TTimeField;
    Qry_rel_osCAMPO_DATARETORNO: TDateField;
    Qry_rel_osCAMPO_HORARETORNO: TTimeField;
    Qry_rel_osCONSUMIDOR_NOME: TStringField;
    Qry_rel_osCONSUMIDOR_ENDERECO: TStringField;
    Qry_rel_osCONSUMIDOR_CPFCNPJ: TStringField;
    Qry_rel_osCONSUMIDOR_TELEFONE: TStringField;
    Qry_rel_osPRAZO_DATACONCLUSAO: TDateField;
    Qry_rel_osPRAZO_HORACONCLUSAO: TTimeField;
    Qry_rel_osMODELO: TStringField;
    Qry_rel_osOBS: TStringField;
    Qry_rel_osID_VENDA: TIntegerField;
    Qry_rel_osDATA_ALTERACAO: TSQLTimeStampField;
    Qry_rel_osOCORRENCIA: TStringField;
    Qry_rel_osOBSEQUIPAMENTO: TStringField;
    Qry_rel_osSOLUCAO: TStringField;
    Qry_rel_osREVENDEDOR: TStringField;
    Qry_rel_osMODALIDADE: TStringField;
    Qry_rel_osGARANTIA: TStringField;
    Qry_rel_osLACRE: TStringField;
    Qry_rel_osGARANTIA_CAMPO1: TStringField;
    Qry_rel_osDATA_PROXIMAREVISAO: TDateField;
    Qry_rel_osCONSUMIDOR_RGINSCR: TStringField;
    Qry_rel_osHORA_INICIO_ATEND: TTimeField;
    Qry_rel_osHORA_FIM_ATEND: TTimeField;
    Qry_rel_osUSERCAD: TStringField;
    Qry_rel_osDATACAD: TDateField;
    Qry_rel_osUSUARIO: TStringField;
    Qry_rel_osMARCA: TStringField;
    Qry_rel_osLOCAL: TStringField;
    Qry_rel_osCOR: TStringField;
    Qry_rel_osMODELO1: TStringField;
    Qry_rel_osSTATUS: TStringField;
    Qry_rel_osTIPO: TStringField;
    Qry_rel_osPRIORIDADE: TStringField;
    Qry_rel_osID_OS_PRIORIDADE1: TIntegerField;
    Qry_rel_osUSERCAD1: TStringField;
    Qry_rel_osDATACAD1: TDateField;
    Qry_rel_osTIPOATENDIMENTO: TStringField;
    cds_rel_osID_OS_ORDEMSERVICO: TIntegerField;
    cds_rel_osID_EMPRESA: TIntegerField;
    cds_rel_osID_OS_PRIORIDADE: TIntegerField;
    cds_rel_osID_OS_TIPOATENDIMENTO: TIntegerField;
    cds_rel_osID_OS_STATUS: TIntegerField;
    cds_rel_osID_CLIENTE: TIntegerField;
    cds_rel_osID_OS_EQUIPAMENTO: TIntegerField;
    cds_rel_osID_OS_EQUIPAMENTO_COR: TIntegerField;
    cds_rel_osID_OS_EQUIP_LOCAL: TIntegerField;
    cds_rel_osID_TECNICORESPONSAVEL: TIntegerField;
    cds_rel_osID_USUARIO: TIntegerField;
    cds_rel_osSITUACAO: TStringField;
    cds_rel_osIDENTIFICADOR: TStringField;
    cds_rel_osEQUIPAMENTO_NSERIE: TStringField;
    cds_rel_osNUMERO_OS: TIntegerField;
    cds_rel_osNOMECONTATO: TStringField;
    cds_rel_osFLAGEXTERNA: TStringField;
    cds_rel_osDATA_ENTRADA: TDateField;
    cds_rel_osHORA_ENTRADA: TTimeField;
    cds_rel_osDATA_SOLUCAO: TDateField;
    cds_rel_osHORA_SOLUCAO: TTimeField;
    cds_rel_osCAMPO_DATAAGENDA: TDateField;
    cds_rel_osCAMPO_HORAAGENDA: TTimeField;
    cds_rel_osCAMPO_DATACHEGADA: TDateField;
    cds_rel_osCAMPO_HORACHEGADA: TTimeField;
    cds_rel_osCAMPO_DATASAIDA: TDateField;
    cds_rel_osCAMPO_HORASAIDA: TTimeField;
    cds_rel_osCAMPO_DATARETORNO: TDateField;
    cds_rel_osCAMPO_HORARETORNO: TTimeField;
    cds_rel_osCONSUMIDOR_NOME: TStringField;
    cds_rel_osCONSUMIDOR_ENDERECO: TStringField;
    cds_rel_osCONSUMIDOR_CPFCNPJ: TStringField;
    cds_rel_osCONSUMIDOR_TELEFONE: TStringField;
    cds_rel_osPRAZO_DATACONCLUSAO: TDateField;
    cds_rel_osPRAZO_HORACONCLUSAO: TTimeField;
    cds_rel_osMODELO: TStringField;
    cds_rel_osOBS: TStringField;
    cds_rel_osID_VENDA: TIntegerField;
    cds_rel_osDATA_ALTERACAO: TSQLTimeStampField;
    cds_rel_osOCORRENCIA: TStringField;
    cds_rel_osOBSEQUIPAMENTO: TStringField;
    cds_rel_osSOLUCAO: TStringField;
    cds_rel_osREVENDEDOR: TStringField;
    cds_rel_osMODALIDADE: TStringField;
    cds_rel_osGARANTIA: TStringField;
    cds_rel_osLACRE: TStringField;
    cds_rel_osGARANTIA_CAMPO1: TStringField;
    cds_rel_osDATA_PROXIMAREVISAO: TDateField;
    cds_rel_osCONSUMIDOR_RGINSCR: TStringField;
    cds_rel_osHORA_INICIO_ATEND: TTimeField;
    cds_rel_osHORA_FIM_ATEND: TTimeField;
    cds_rel_osUSERCAD: TStringField;
    cds_rel_osDATACAD: TDateField;
    cds_rel_osUSUARIO: TStringField;
    cds_rel_osMARCA: TStringField;
    cds_rel_osLOCAL: TStringField;
    cds_rel_osCOR: TStringField;
    cds_rel_osMODELO1: TStringField;
    cds_rel_osSTATUS: TStringField;
    cds_rel_osTIPO: TStringField;
    cds_rel_osPRIORIDADE: TStringField;
    cds_rel_osID_OS_PRIORIDADE1: TIntegerField;
    cds_rel_osUSERCAD1: TStringField;
    cds_rel_osDATACAD1: TDateField;
    cds_rel_osTIPOATENDIMENTO: TStringField;
    SDS_REL_PRODUTOID_OS_PRODUTOS_SERVICOS: TIntegerField;
    SDS_REL_PRODUTOID_OS_ORDEMSERVICO: TIntegerField;
    SDS_REL_PRODUTOID_OS_TECNICO: TIntegerField;
    SDS_REL_PRODUTOCOD_PRODUTO: TIntegerField;
    SDS_REL_PRODUTOCODIGO_BARRAS: TStringField;
    SDS_REL_PRODUTOVALOR_UNITARIO: TFloatField;
    SDS_REL_PRODUTOQUANTIDADE: TFloatField;
    SDS_REL_PRODUTOPERC_DESCONTO: TFloatField;
    SDS_REL_PRODUTOVLRDESCONTO: TFloatField;
    SDS_REL_PRODUTOVALOR_TOTAL: TFloatField;
    SDS_REL_PRODUTODESC_UNIDADE: TStringField;
    SDS_REL_PRODUTODTFIMPROMVAREJO: TDateField;
    SDS_REL_PRODUTODTINICIOPROMVAREJO: TDateField;
    SDS_REL_PRODUTOVALGRAMASAIDA: TFloatField;
    SDS_REL_PRODUTOESTAPROMOCAOVAREJO: TStringField;
    SDS_REL_PRODUTOEMBALAGEMSAIDA: TStringField;
    SDS_REL_PRODUTOPRECO_ATUAL_MANTIDO: TFloatField;
    SDS_REL_PRODUTODESCRICAO: TStringField;
    SDS_REL_PRODUTOPROD_SERV: TStringField;
    SDS_REL_PRODUTOSIT_TRIBUTARIA: TStringField;
    SDS_REL_PRODUTOFRACAO: TIntegerField;
    SDS_REL_PRODUTOCOD_NCM: TStringField;
    SDS_PRODUTOSID_OS_PRODUTOS_SERVICOS: TIntegerField;
    SDS_PRODUTOSID_OS_ORDEMSERVICO: TIntegerField;
    SDS_PRODUTOSID_OS_TECNICO: TIntegerField;
    SDS_PRODUTOSCOD_PRODUTO: TIntegerField;
    SDS_PRODUTOSCODIGO_BARRAS: TStringField;
    SDS_PRODUTOSVALOR_UNITARIO: TFloatField;
    SDS_PRODUTOSQUANTIDADE: TFloatField;
    SDS_PRODUTOSPERC_DESCONTO: TFloatField;
    SDS_PRODUTOSVLRDESCONTO: TFloatField;
    SDS_PRODUTOSVALOR_TOTAL: TFloatField;
    SDS_PRODUTOSDESC_UNIDADE: TStringField;
    SDS_PRODUTOSDTFIMPROMVAREJO: TDateField;
    SDS_PRODUTOSDTINICIOPROMVAREJO: TDateField;
    SDS_PRODUTOSVALGRAMASAIDA: TFloatField;
    SDS_PRODUTOSESTAPROMOCAOVAREJO: TStringField;
    SDS_PRODUTOSEMBALAGEMSAIDA: TStringField;
    SDS_PRODUTOSPRECO_ATUAL_MANTIDO: TFloatField;
    SDS_PRODUTOSDESCRICAO: TStringField;
    SDS_PRODUTOSPROD_SERV: TStringField;
    SDS_PRODUTOSSIT_TRIBUTARIA: TStringField;
    SDS_PRODUTOSFRACAO: TIntegerField;
    SDS_PRODUTOSCOD_NCM: TStringField;
    sDS_EQUIPAMENTOS: TSimpleDataSet;
    sDS_EQUIPAMENTOSID_OS_EQUIPAMENTOS: TIntegerField;
    sDS_EQUIPAMENTOSID_OS_EQUIPAMENTO_TIPO: TIntegerField;
    sDS_EQUIPAMENTOSID_OS_EQUIPAMENTO_MARCA: TIntegerField;
    sDS_EQUIPAMENTOSMODELO: TStringField;
    sDS_EQUIPAMENTOSID_OS_EQUIPAMENTOS_STR: TStringField;
    sDS_EQUIPAMENTOSTIPO: TStringField;
    sDS_EQUIPAMENTOSMARCA: TStringField;
    Dts_equipamentos: TDataSource;
    SDS_OSNOTAFISCAL: TStringField;
    SDS_OSDATA_NOTAFISCAL: TDateField;
    SDS_OSKM: TIntegerField;
    SDS_OSPLACA: TStringField;
    SDS_OSVEICULO: TStringField;
    Qry_rel_osKM: TIntegerField;
    Qry_rel_osPLACA: TStringField;
    Qry_rel_osVEICULO: TStringField;
    cds_rel_osKM: TIntegerField;
    cds_rel_osPLACA: TStringField;
    cds_rel_osVEICULO: TStringField;
    procedure DataModuleCreate(Sender: TObject);
    procedure SDS_OS_PRODUTOAfterPost(DataSet: TDataSet);
    procedure SDS_OS_PRODUTOAfterScroll(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DMOS: TDMOS;

implementation

uses ModulodeDados, OSLancamento;

{$R *.dfm}

procedure TDMOS.DataModuleCreate(Sender: TObject);
begin
{with DM.SQLC do
begin
Close;
Params.Clear;
Params.LoadFromFile('C:\siace\siace.ini');
Open;
end;}
end;
procedure TDMOS.SDS_OS_PRODUTOAfterPost(DataSet: TDataSet);
begin
DMOS.SDS_OS_PRODUTO.First;
FormOs.A := 0;
FormOs.A := FormOs.A + DMOS.SDS_OS_PRODUTOVALOR_TOTAL.AsFloat;
FormOs.B := FormOs.B + DMOS.SDS_OS_PRODUTOVALOR_UNITARIO.AsFloat;
FormOs.C := FormOs.C + DMOS.SDS_OS_PRODUTOVLRDESCONTO.AsFloat;
DMOS.SDS_OS_PRODUTO.Next;
FormOs.Edit60.Text := FloatToStr(FormOs.B);
FormOs.Edit61.Text := FloatToStr(FormOs.C);
FormOs.Edit62.Text := FloatToStr(FormOs.A);
While not DMOS.SDS_OS_PRODUTO.Eof do
begin
FormOs.A:= FormOs.A + DMOS.SDS_OS_PRODUTOVALOR_TOTAL.AsFloat;
FormOs.B := FormOs.B + DMOS.SDS_OS_PRODUTOVALOR_UNITARIO.AsFloat;
FormOs.C := FormOs.C + DMOS.SDS_OS_PRODUTOVLRDESCONTO.AsFloat;
DMOS.SDS_OS_PRODUTO.Next;
FormOs.Edit60.Text := FloatToStr(FormOs.B);
FormOs.Edit61.Text := FloatToStr(FormOs.C);
FormOs.Edit62.Text := FloatToStr(FormOs.A);
end;
DMOS.SDS_OS_PRODUTO.last;
end;

procedure TDMOS.SDS_OS_PRODUTOAfterScroll(DataSet: TDataSet);
begin
{DMOS.SDS_OS_PRODUTO.First;
FormOs.A := 0;
FormOs.B := 0;
FormOs.C := 0;
FormOs.A := FormOs.A + DMOS.SDS_OS_PRODUTOVALOR_TOTAL.AsFloat;
FormOs.B := FormOs.B + DMOS.SDS_OS_PRODUTOVALOR_UNITARIO.AsFloat;
FormOs.C := FormOs.C + DMOS.SDS_OS_PRODUTOVLRDESCONTO.AsFloat;
DMOS.SDS_OS_PRODUTO.Next;
FormOs.Edit60.Text := FloatToStr(FormOs.B);
FormOs.Edit61.Text := FloatToStr(FormOs.C);
FormOs.Edit62.Text := FloatToStr(FormOs.A);
While not DMOS.SDS_OS_PRODUTO.Eof do
begin
FormOs.A:= FormOs.A + DMOS.SDS_OS_PRODUTOVALOR_TOTAL.AsFloat;
FormOs.B := FormOs.B + DMOS.SDS_OS_PRODUTOVALOR_UNITARIO.AsFloat;
FormOs.C := FormOs.C + DMOS.SDS_OS_PRODUTOVLRDESCONTO.AsFloat;
DMOS.SDS_OS_PRODUTO.Next;
FormOs.Edit60.Text := FloatToStr(FormOs.B);
FormOs.Edit61.Text := FloatToStr(FormOs.C);
FormOs.Edit62.Text := FloatToStr(FormOs.A);
end;
DMOS.SDS_OS_PRODUTO.last;  }
end;

end.
